// Named functions
export declare function BountyCancelLegendaryMission(): void;
export declare function BountyCancelWantedPoster(): void;
export declare function BountyClearBeingBountyHunter(): void;
export declare function BountyClearBeingTarget(): void;
export declare function BountyGetBountyOnPlayer(): [boolean, any, any];
export declare function BountyGetCooldownCollection(): [any, any];
export declare function BountyGetLegendaryTarget(p0: any): [boolean, any];
export declare function BountyGetWantedPosterSlot(p0: string | number, p1: string | number): [boolean, any];
export declare function BountyIsRequestPending(): [boolean, any];
export declare function BountyRequestBecomeTargetOfCharacterBountyHunt(): [boolean, any];
export declare function BountyRequestBeginLegendaryMission(p1: number, p2: number): [boolean, any];
export declare function BountyRequestBeginLegendaryMissionForPosse(p1: number, p2: number): [boolean, any];
export declare function BountyRequestBeginWantedPoster(p1: number): [boolean, any];
export declare function BountyRequestBribeJailGuard(p1: number): [boolean, any];
export declare function BountyRequestClaimCharacterBounty(p1: number): [boolean, any, any];
export declare function BountyRequestCompleteLegendaryMission(): [boolean, any, any];
export declare function BountyRequestCompleteSplitWantedPoster(): [boolean, any, any];
export declare function BountyRequestCompleteWantedPoster(): [boolean, any, any];
export declare function BountyRequestEscapedCharacterBountyHunt(): [boolean, any];
export declare function BountyRequestPayOffBounty(): [boolean, any];
export declare function BountyRequestPayOffBountyEx(p1: string | number, costType: string | number): [boolean, any];
export declare function BountyRequestPosseLeaderClaimCharacterBounty(p1: number): [boolean, any, any];
export declare function BountyRequestPosseLeaderEscapedCharacterBountyHunt(): [boolean, any];
export declare function BountyRequestPosseMemberClaimCharacterBountyShare(): [boolean, any, any];
export declare function BountyRequestPosseMemberEscapedCharacterBountyHunt(): [boolean, any];
export declare function BountyRequestSelfReportCrime(crimeType: string | number, p2: boolean): [boolean, any];
export declare function BountyRequestSelfReportKilledByBountyHunter(): [boolean, any];
export declare function BountyRequestServedFullJailSentence(): [boolean, any];
// Hash functions
export declare function N_0x27d3a0e1fe090a43(): [boolean, any];
export declare function N_0x81847c2134039bdc(): [boolean, any];
export declare function N_0xd6a67e2ff373d0e3(p0: number): number;
export declare function N_0xf8bcc5eca33ac9c1(): number;
