// Named functions
export declare function AddCamSplineNode(camera: number, x: number, y: number, z: number, xRot: number, yRot: number, zRot: number, length: number, p8: number, p9: number): void;
export declare function AnimateGameplayCamZoom(p0: number, distance: number): void;
export declare function AttachCamToEntity(cam: number, entity: number, xOffset: number, yOffset: number, zOffset: number, isRelative: boolean): void;
export declare function AttachCamToPedBone(cam: number, ped: number, boneIndex: number, x: number, y: number, z: number, heading: boolean): void;
export declare function CinematicLocationStopScriptedShotEvent(p0: any, p1: any, p2: any): void;
export declare function CinematicLocationTriggerScriptedShotEvent(p0: any, p1: any, p2: any, p3: any): void;
export declare function ClampGameplayCamPitch(minimum: number, maximum: number): void;
export declare function ClampGameplayCamYaw(minimum: number, maximum: number): void;
export declare function CreateCam(p1: boolean): [number, const char];
export declare function CreateCamera(camHash: string | number, p1: boolean): number;
export declare function CreateCameraWithParams(camHash: string | number, posX: number, posY: number, posZ: number, rotX: number, rotY: number, rotZ: number, fov: number, p8: boolean, p9: any): number;
export declare function CreateCamWithParams(posX: number, posY: number, posZ: number, rotX: number, rotY: number, rotZ: number, fov: number, p8: boolean, p9: number): [number, const char];
export declare function DestroyAllCams(p0: boolean): void;
export declare function DestroyCam(cam: number, p1: boolean): void;
export declare function DetachCam(cam: number): void;
export declare function DisableCamCollisionForObject(entity: number): void;
export declare function DisableFirstPersonCamThisFrame(): void;
export declare function DisableFirstPersonCamThisFrame2(): void;
export declare function DisableVehicleFirstPersonCamThisFrame(): void;
export declare function DoesCamExist(cam: number): boolean;
export declare function DoScreenFadeIn(duration: number): void;
export declare function DoScreenFadeOut(duration: number): void;
export declare function ForceCinematicRenderingThisUpdate(p0: boolean): void;
export declare function FreezeGameplayCamThisFrame(): void;
export declare function GetCamCoord(cam: number): [number, number, number];
export declare function GetCamFov(cam: number): number;
export declare function GetCamRot(cam: number, rotationOrder: number): [number, number, number];
export declare function GetCamSplinePhase(cam: number): number;
export declare function GetFinalRenderedCamCoord(): [number, number, number];
export declare function GetFinalRenderedCamFov(): number;
export declare function GetFinalRenderedCamRot(rotationOrder: number): [number, number, number];
export declare function GetFirstPersonAimCamZoomFactor(): number;
export declare function GetGameplayCamCoord(): [number, number, number];
export declare function GetGameplayCamFov(): number;
export declare function GetGameplayCamRelativeHeading(): number;
export declare function GetGameplayCamRelativePitch(): number;
export declare function GetGameplayCamRot(rotationOrder: number): [number, number, number];
export declare function GetPhotoModeDof(): number;
export declare function GetPhotoModeFocalLength(): number;
export declare function GetPhotoModeFocusDistance(): number;
export declare function GetRenderingCam(): number;
export declare function IsAimCamActive(): boolean;
export declare function IsCamActive(cam: number): boolean;
export declare function IsCamInterpolating(cam: number): boolean;
export declare function IsCamRendering(cam: number): boolean;
export declare function IsCamShaking(cam: number): boolean;
export declare function IsCinematicCamRendering(): boolean;
export declare function IsDeathFailCameraRunning(): boolean;
export declare function IsFirstPersonAimCamActive(): boolean;
export declare function IsFirstPersonCameraActive(p0: any, p1: any, p2: any): boolean;
export declare function IsFollowVehicleCamActive(): boolean;
export declare function IsGameplayCamLookingBehind(): boolean;
export declare function IsGameplayCamRendering(): boolean;
export declare function IsGameplayCamShaking(): boolean;
export declare function IsGameplayHintActive(): boolean;
export declare function IsScreenFadedIn(): boolean;
export declare function IsScreenFadedOut(): boolean;
export declare function IsScreenFadingIn(): boolean;
export declare function IsScreenFadingOut(): boolean;
export declare function IsSphereVisible(x: number, y: number, z: number, radius: number): boolean;
export declare function PlayCamAnim(cam: number, x: number, y: number, z: number, xRot: number, yRot: number, zRot: number, p9: boolean, p10: number): [boolean, const char, const char];
export declare function PointCamAtCoord(cam: number, x: number, y: number, z: number): void;
export declare function PointCamAtEntity(cam: number, entity: number, p2: number, p3: number, p4: number, p5: boolean): void;
export declare function RenderScriptCams(render: boolean, ease: boolean, easeTime: number, p3: boolean, p4: boolean, p5: any): void;
export declare function SetCamActive(cam: number, active: boolean): void;
export declare function SetCamActiveWithInterp(camTo: number, camFrom: number, duration: number, easeLocation: number, easeRotation: number): void;
export declare function SetCamAffectsAiming(cam: number, toggle: boolean): void;
export declare function SetCamCoord(cam: number, posX: number, posY: number, posZ: number): void;
export declare function SetCamFarClip(cam: number, farClip: number): void;
export declare function SetCamFocusDistance(cam: number, distance: number): void;
export declare function SetCamFov(cam: number, fieldOfView: number): void;
export declare function SetCamMotionBlurStrength(cam: number, strength: number): void;
export declare function SetCamNearClip(cam: number, nearClip: number): void;
export declare function SetCamParams(cam: number, posX: number, posY: number, posZ: number, rotX: number, rotY: number, rotZ: number, fieldOfView: number, p8: any, p9: number, p10: number, p11: number, p12: any, p13: any): void;
export declare function SetCamRot(cam: number, rotX: number, rotY: number, rotZ: number, rotationOrder: number): void;
export declare function SetCamSplineDuration(cam: number, timeDuration: number): void;
export declare function SetCamSplinePhase(cam: number, p1: number): void;
export declare function SetCamSplineSmoothingStyle(cam: number, smoothingStyle: number): void;
export declare function SetCinematicButtonActive(p0: boolean): void;
export declare function SetCinematicModeActive(p0: boolean): void;
export declare function SetFirstPersonCamPitchRange(p0: number, p1: number): void;
export declare function SetGameplayCamFollowPedThisUpdate(p0: any): void;
export declare function SetGameplayCamRelativeHeading(heading: number, p1: number): void;
export declare function SetGameplayCamRelativePitch(x: number, Value2: number): void;
export declare function SetGameplayCamShakeAmplitude(amplitude: number): void;
export declare function SetGameplayCoordHint(x: number, y: number, z: number, duration: number, blendOutDuration: number, blendInDuration: number, unk: number): void;
export declare function SetGameplayEntityHint(entity: number, xOffset: number, yOffset: number, zOffset: number, p4: boolean, p5: number, p6: number, p7: number, p8: any): void;
export declare function SetGameplayHintAnimOffsetx(p0: number): void;
export declare function SetGameplayHintAnimOffsety(p0: number): void;
export declare function SetGameplayHintBaseOrbitPitchOffset(p0: number): void;
export declare function SetGameplayHintFollowDistanceScalar(p0: number): void;
export declare function SetGameplayHintFov(FOV: number): void;
export declare function SetGameplayObjectHint(p0: any, p1: number, p2: number, p3: number, p4: boolean, p5: any, p6: any, p7: any): void;
export declare function SetGameplayPedHint(p0: number, x1: number, y1: number, z1: number, p4: boolean, p5: any, p6: any, p7: any): void;
export declare function SetGameplayVehicleHint(p0: any, p1: number, p2: number, p3: number, p4: boolean, p5: any, p6: any, p7: any): void;
export declare function SetInVehicleCamStateThisUpdate(p0: number, p1: number): void;
export declare function SetWidescreenBorders(p0: boolean, p1: number): void;
export declare function ShakeCam(cam: number, amplitude: number): const char;
export declare function ShakeGameplayCam(intensity: number): const char;
export declare function StopCamPointing(cam: number): void;
export declare function StopCamShaking(cam: number, p1: boolean): void;
export declare function StopGameplayCamShaking(p0: boolean): void;
export declare function StopGameplayHint(p0: boolean): void;
export declare function StopRenderingScriptCamsUsingCatchUp(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): void;
export declare function TriggerMissionFailedCam(): void;
// Hash functions
export declare function N_0x0060b31968e60e41(p0: any): any;
export declare function N_0x04084490cc302cfb(): void;
export declare function N_0x05bd5e4088b30a66(p0: number, p1: number): void;
export declare function N_0x06557f6d96c86881(): void;
export declare function N_0x066167c63111d8cf(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function N_0x0961b089947ba6d0(p0: any): void;
export declare function N_0x0a5a4f1979abb40e(p0: any): void;
export declare function N_0x0b0f914459731f60(p0: any, p1: any): void;
export declare function N_0x0e94c95ec3185fa9(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): void;
export declare function N_0x0f1ffef5d54ae832(): void;
export declare function N_0x0ff7125f07deb84f(p0: any, p1: any): void;
export declare function N_0x1204eb53a5fbc63d(): any;
export declare function N_0x14c4a49e36c29e49(): any;
export declare function N_0x16e9abdd34ddd931(): void;
export declare function N_0x1811a02277a9e49d(): boolean;
export declare function N_0x18c3dfac458783bb(): void;
export declare function N_0x190f7da1ac09a8ef(): any;
export declare function N_0x1b3c2d961f5fc0e1(p0: any): void;
export declare function N_0x1b8f3ce5a6001298(cam: number, p1: boolean): void;
export declare function N_0x1cfb749ad4317bde(): void;
export declare function N_0x1d9f72dd4fd9a9d7(p0: any): void;
export declare function N_0x1dd95a8d6b24a0c9(p0: boolean): void;
export declare function N_0x1f6ebd94680252ce(p0: any, p1: any): void;
export declare function N_0x1fc6c727d30ffdde(p0: any): void;
export declare function N_0x20389408f0e93b9a(): any;
export declare function N_0x2412216fcc7b4e3e(p0: any): void;
export declare function N_0x251241caec707106(): boolean;
export declare function N_0x29e6655df3590b0d(p0: any): void;
export declare function N_0x2ab7c81b3f70570c(): any;
export declare function N_0x2dd3149dc34a3f4c(p0: any): void;
export declare function N_0x2f994cc29caa9d22(p0: any): void;
export declare function N_0x39073da4eddbc91d(p0: any): void;
export declare function N_0x3b8e3ad9677ce12b(p0: any, p1: any, p2: any): void;
export declare function N_0x3c486e334520579d(): void;
export declare function N_0x3c8f74e8fe751614(): void;
export declare function N_0x4138ee36bc3dc0a7(p0: any, p1: any): any;
export declare function N_0x41e452a3c580d1a7(): void;
export declare function N_0x4285804fd65d8066(p0: any, p1: any): void;
export declare function N_0x42ed56b02e05d109(p0: any, p1: boolean): void;
export declare function N_0x43ab9d5a7d415478(): boolean;
export declare function N_0x449995ea846d3fc2(p0: any): void;
export declare function N_0x450769c833d58844(): any;
export declare function N_0x465f04f68ad38197(p0: any, p1: any, p2: any): any;
export declare function N_0x4d2f46d1b28d90fb(p0: any, p1: any): void;
export declare function N_0x5060fa977cea4455(): any;
export declare function N_0x595550376b7ea230(p0: any): any;
export declare function N_0x5b637d6f3b67716a(p0: any): void;
export declare function N_0x6072b7420a83a03f(): any;
export declare function N_0x632be8d84846fa56(): void;
export declare function N_0x634f4a0562cf19b8(): void;
export declare function N_0x63e5841a9264d016(p0: any): void;
export declare function N_0x641092322a8852ab(): void;
export declare function N_0x6519238858af5479(p0: any): void;
export declare function N_0x65b205bf30c13ddb(p0: any): void;
export declare function N_0x69d65e89ffd72313(p0: any, p1: any): void;
export declare function N_0x6a4d224fc7643941(p0: any): void;
export declare function N_0x6c1053c433a573cf(p0: any): void;
export declare function N_0x6cab0ba160b168d2(): void;
export declare function N_0x6dfd37e586d4f44f(): any;
export declare function N_0x6e969927cf632608(p0: any): void;
export declare function N_0x70a6658d476c6187(): void;
export declare function N_0x718c6ecf5e8cbdd4(): void;
export declare function N_0x71d71e08a7ed5bd7(p0: any): void;
export declare function N_0x728491fb3dffef99(p0: any): void;
export declare function N_0x73ff6be63dc18819(): any;
export declare function N_0x74f1d22efa71fab8(): any;
export declare function N_0x77d65669a05d1a1a(): void;
export declare function N_0x796085220adcc847(): any;
export declare function N_0x798be43c9393632b(p0: any): void;
export declare function N_0x7b0279170961a73f(p0: any): void;
export declare function N_0x7ce9dc58e3e4755f(): any;
export declare function N_0x7e40a01b11398fcb(): void;
export declare function N_0x80d7a3e39b120bc4(): any;
export declare function N_0x81dcfd13cf39920e(): any;
export declare function N_0x8370d34bd2e60b73(): void;
export declare function N_0x8459b3e64257b21d(p0: number): void;
export declare function N_0x8505e05fc8822843(p0: any): void;
export declare function N_0x88544c0e3291dcae(p0: any): void;
export declare function N_0x8910c24b7e0046ec(): void;
export declare function N_0x8b1a5fe7e41e52b2(): any;
export declare function N_0x8e036b41c37d0e5f(p0: any): void;
export declare function N_0x90da5ba5c2635416(): any;
export declare function N_0x927b810e43e99932(p0: any): any;
export declare function N_0x93759a83d0d844e7(p0: boolean): void;
export declare function N_0x975f6ebb62632fe3(): any;
export declare function N_0x986f7a51ee3e1f92(p0: any, p1: any): void;
export declare function N_0x9ac65a36d3c0c189(p0: any): void;
export declare function N_0x9f97e85ec142255e(p0: any, p1: any): void;
export declare function N_0xa14d5fe82bcb1d9e(): any;
export declare function N_0xa2b1c7ef759a63ce(): any;
export declare function N_0xa54d643d0773eb65(p0: any, p1: any, p2: any): void;
export declare function N_0xa8ba2e0204d8486f(): void;
export declare function N_0xaa235e2f2c09e952(p0: any): any;
export declare function N_0xac77757c05de9e5a(p0: any): void;
export declare function N_0xb6a80e1e3a5444f1(): any;
export declare function N_0xb85c13e0bf1f2a1c(p0: any): void;
export declare function N_0xb8b207c34285e978(p0: any): void;
export declare function N_0xbc016635d6a73b31(p0: any, p1: any, p2: any): void;
export declare function N_0xbcda0ba8762facb9(p0: any): void;
export declare function N_0xc205b3c54c6a4e37(p0: any): void;
export declare function N_0xc252c0cc969af79a(p0: any): void;
export declare function N_0xc285fd21294a1c49(p0: any): any;
export declare function N_0xc3742f1fdf0a6824(): void;
export declare function N_0xc3e9e5d4f413b773(p0: any, p1: any): void;
export declare function N_0xc64abc0676af262b(): void;
export declare function N_0xcf69ea05cd9c33c9(): void;
export declare function N_0xd1ba66940e94c547(): any;
export declare function N_0xd904f75dbd7ab865(entity: number): void;
export declare function N_0xdb382fe20c2da222(p0: any): void;
export declare function N_0xdc62cd70658e7a02(): any;
export declare function N_0xdd0b7c5ae58f721d(p0: any): any;
export declare function N_0xdf7f5be9150e47e4(p0: any): void;
export declare function N_0xe28f73212a813e82(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0xe296208c273bd7f0(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): void;
export declare function N_0xe2bb2d6a9fe2ecde(p0: any): void;
export declare function N_0xe3639db78b3b5400(p0: any): void;
export declare function N_0xe4b7945ef4f1bfb2(p0: any, p1: any): void;
export declare function N_0xe6f364de6c2fdefe(): void;
export declare function N_0xea113bf9b0c0c5d7(p0: any, p1: any, p2: any): any;
export declare function N_0xef9a3132a0aa6b19(): any;
export declare function N_0xf1a6feedf3776ef9(): void;
export declare function N_0xf48664e9c83825e3(p0: any, p1: any): void;
export declare function N_0xf824530b612fe0ce(): any;
export declare function N_0xfc3f638be2b6bb02(): void;
export declare function N_0xfeb8646818294c75(p0: any, p1: any): void;
export declare function N_0xfefddc6e8fdf8a75(p0: any, p1: any): void;
