// Named functions
export declare function CompendiumAnimalGetSampleInventoryItem(p0: any): any;
export declare function CompendiumAnimalHasSample(p0: any): any;
export declare function CompendiumAnimalHasStamp(p0: any): any;
export declare function CompendiumAnimalObservedByStatName(p0: any, p1: any): void;
export declare function CompendiumAnimalSetDiscovered(p0: any): void;
export declare function CompendiumFishCaught(p0: any, p1: any): void;
export declare function CompendiumFishGetLureSuitabilityByStatItem(p0: any, p1: any): any;
export declare function CompendiumGangAmbushSurvived(p0: any): void;
export declare function CompendiumGangBountyCaptured(p0: any): void;
export declare function CompendiumGangCampFound(p0: any, p1: any): void;
export declare function CompendiumGangEncountered(p0: any): void;
export declare function CompendiumGangHideoutFound(p0: any, p1: any): void;
export declare function CompendiumGangMemberKilled(p0: any): void;
export declare function CompendiumGetEntryByIndexInSubcategory(p0: any, p1: any, p2: any): any;
export declare function CompendiumGetEntryByStatItem(p0: any, p1: any): any;
export declare function CompendiumGetMapDiscoverableFromStatItem(p0: any, p1: any, p2: any, p3: any): any;
export declare function CompendiumGetNumEntriesInSubcategory(p0: any, p1: any): any;
export declare function CompendiumGetShortDescriptionFromPed(p0: any): any;
export declare function CompendiumGetSubcategorySampleToastDescComplete(p0: any, p1: any): any;
export declare function CompendiumGetSubcategorySampleToastDescProgress(p0: any, p1: any): any;
export declare function CompendiumGetSubcategorySampleToastTitle(p0: any, p1: any): any;
export declare function CompendiumGetSubcategoryToastAppId(p0: any, p1: any): any;
export declare function CompendiumHerbPicked(herbType: string | number, x: number, y: number, z: number): void;
export declare function CompendiumHorseBonding(p0: any, p1: any): void;
export declare function CompendiumHorseObserved(p0: any, p1: any): void;
export declare function CompendiumHorseWildBroken(p0: any): void;
// Hash functions
export declare function N_0x1cfa0219d8e1cf25(p0: any, p1: any): any;
export declare function N_0x23b5e9c5160bc04f(p0: any): any;
export declare function N_0x725d52f21a5e9e22(p0: any): any;
export declare function N_0x729d52461aea9e22(p0: any): any;
export declare function N_0x729d52f61a5a9e22(p0: any): any;
export declare function N_0x9b657550df55ec96(p0: any, p1: any): any;
export declare function N_0x9f678782720349e4(p0: any): any;
export declare function N_0xcd278b6bfbdbdc22(p0: any, p1: any): any;
