// Named functions
export declare function DatabindingAddDataBool(p0: any, p1: any, p2: any): any;
export declare function DatabindingAddDataBoolByHash(p0: any, p1: any, p2: any): any;
export declare function DatabindingAddDataBoolFromPath(p0: any, p1: any, p2: any): any;
export declare function DatabindingAddDataContainer(p0: any, p1: any): any;
export declare function DatabindingAddDataContainerByHash(p0: any, p1: any): any;
export declare function DatabindingAddDataContainerFromPath(p0: any, p1: any): any;
export declare function DatabindingAddDataFloat(p0: any, p1: any, p2: any): any;
export declare function DatabindingAddDataGangId(p0: any, p1: any, p2: any): any;
export declare function DatabindingAddDataHash(p0: any, p1: any, p2: any): any;
export declare function DatabindingAddDataHashByHash(p0: any, p1: any, p2: any): any;
export declare function DatabindingAddDataInt(p0: any, p1: any, p2: any): any;
export declare function DatabindingAddDataIntByHash(p0: any, p1: any, p2: any): any;
export declare function DatabindingAddDataString(p0: any, p1: any, p2: any): any;
export declare function DatabindingAddDataStringByHash(p0: any, p1: any, p2: any): any;
export declare function DatabindingAddDataStringFromPath(): [any, string, string, string];
export declare function DatabindingAddHashArray(p0: any, p1: any): any;
export declare function DatabindingAddStringArray(p0: any, p1: any): any;
export declare function DatabindingAddUiItemList(p0: any, p1: any): any;
export declare function DatabindingAddUiItemListByHash(p0: any, p1: any): any;
export declare function DatabindingAddUiItemListFromPath(p0: any, p1: any): any;
export declare function DatabindingClearBindingArray(p0: any): void;
export declare function DatabindingGetArrayCount(p0: any): any;
export declare function DatabindingGetDataContainerFromChildIndex(p0: any, p1: any): any;
export declare function DatabindingGetDataContainerFromPath(p0: any): any;
export declare function DatabindingGetItemContextByIndex(p0: any, p1: any): any;
export declare function DatabindingInsertUiItemToListFromContextHashAlias(p0: any, p1: any, p2: any, p3: any): void;
export declare function DatabindingInsertUiItemToListFromContextStringAlias(p0: any, p1: any, p2: any, p3: any): void;
export declare function DatabindingInsertUiItemToListFromPathStringAlias(p0: any, p1: any, p2: any, p3: any): void;
export declare function DatabindingIsEntryValid(entryId: string | number): boolean;
export declare function DatabindingReadDataBool(p0: any): any;
export declare function DatabindingReadDataBoolFromParent(p0: any, p1: any): any;
export declare function DatabindingReadDataBoolFromParentByHash(p0: any, p1: any): any;
export declare function DatabindingReadDataHashStringFromParent(p0: any, p1: any): any;
export declare function DatabindingReadDataHashStringFromParentByHash(p0: any, p1: any): any;
export declare function DatabindingReadDataIntFromParent(p0: any, p1: any): any;
export declare function DatabindingReadDataIntFromParentByHash(p0: any, p1: any): any;
export declare function DatabindingReadDataString(p0: any): any;
export declare function DatabindingReadDataStringFromParent(p0: any, p1: any): any;
export declare function DatabindingReadInt(p0: any): any;
export declare function DatabindingRemoveBindingArrayItemByDataContextId(p0: any, p1: any): void;
export declare function DatabindingRemoveDataEntry(p0: any): void;
export declare function DatabindingSetTemplatedUiItemHashAlias(p0: any, p1: any, p2: any): void;
export declare function DatabindingSetTemplatedUiItemListSize(p0: any, p1: any): void;
export declare function DatabindingWriteDataBool(p0: any, p1: any): void;
export declare function DatabindingWriteDataBoolFromParent(p0: any, p1: any, p2: any): void;
export declare function DatabindingWriteDataFloat(p0: any, p1: any): void;
export declare function DatabindingWriteDataHashString(p0: any, p1: any): void;
export declare function DatabindingWriteDataHashStringFromParent(p0: any, p1: any, p2: any): void;
export declare function DatabindingWriteDataHashStringFromParentByHash(p0: any, p1: any, p2: any): void;
export declare function DatabindingWriteDataInt(p0: any, p1: any): void;
export declare function DatabindingWriteDataIntFromParent(p0: any, p1: any, p2: any): void;
export declare function DatabindingWriteDataIntFromParentByHash(p0: any, p1: any, p2: any): void;
export declare function DatabindingWriteDataScriptVariables(p0: any, p1: any, ...args: any[]): void;
export declare function DatabindingWriteDataString(p0: any, p1: any): void;
export declare function DatabindingWriteStringFromParent(p0: any, p1: any, p2: any): void;
export declare function VirtualCollectionExists(p0: any): any;
export declare function VirtualCollectionItemAdd(p0: any, p1: any, p2: any, p3: any): void;
export declare function VirtualCollectionReset(p0: any): void;
export declare function VirtualCollectionSetInterestIndex(p0: any, p1: any): void;
export declare function VirtualCollectionSetSize(p0: any, p1: any): void;
// Hash functions
export declare function N_0x02b21b6beedd83cc(p0: any, p1: any): any;
export declare function N_0x05ac9e1e02975afb(p0: any, p1: any, p2: any): void;
export declare function N_0x1919d59e60fd516e(p0: any, p1: any, p2: any): void;
export declare function N_0x294af5323f44b053(p0: any, p1: any, p2: any): any;
export declare function N_0x3bf0767cf33fcc88(p0: any): void;
export declare function N_0x422179c7f6ad9304(p0: any, p1: any): void;
export declare function N_0x5fe444eb67c70ad4(p0: any): any;
export declare function N_0x6318fb3be37e11b3(p0: any, p1: any): void;
export declare function N_0x6329c34bee5bff4b(p0: any, p1: any): any;
export declare function N_0x7d0f2014db28dd01(p0: any, p1: any, p2: any): any;
export declare function N_0x7fc60c94c83c5cd7(p0: any, p1: any, p2: any): void;
export declare function N_0x81d7183e7a8eca72(p0: any): any;
export declare function N_0xa3bd6ff95e713ee5(p0: any, p1: any, p2: any): void;
export declare function N_0xb138ca787f3dd858(p0: any, p1: any, p2: any): void;
export declare function N_0xbfc83da249befcc9(p0: any, p1: any, p2: any): void;
export declare function N_0xc70041408e16be2d(p0: any, p1: any, p2: any): void;
export declare function N_0xc70041408e16be2e(p0: any, p1: any, p2: any): void;
export declare function N_0xc900cec8a172375b(p0: any, p1: any, p2: any): void;
export declare function N_0xd48993a61938c64d(p0: any, p1: any): any;
export declare function N_0xd7db94ab78e8ebe4(p0: any, p1: any): any;
export declare function N_0xe6aab897120492d6(p0: any, p1: any): any;
export declare function N_0xe6aab897120492d7(p0: any, p1: any, p2: any): void;
export declare function N_0xf47e33f8d2523825(p0: any, p1: any): any;
