// Named functions
export declare function ArrayValueGetBoolean(arrayIndex: number): [boolean, any];
export declare function ArrayValueGetFloat(arrayIndex: number): [number, any];
export declare function ArrayValueGetInteger(arrayIndex: number): [number, any];
export declare function ArrayValueGetObject(arrayIndex: number): [any, any];
export declare function ArrayValueGetSize(): [number, any];
export declare function ArrayValueGetString(arrayIndex: number): [string, any];
export declare function ArrayValueGetType(arrayIndex: number): [number, any];
export declare function ArrayValueGetVector3(arrayIndex: number): [[number, number, number], any];
export declare function DatafileCreate(index: number): void;
export declare function DatafileDelete(index: number): void;
export declare function DatafileDeleteRequestedFile(p0: any): boolean;
export declare function DatafileGetBool(p0: any, p1: any): any;
export declare function DatafileGetDataNodeIndex(p0: any, p1: any): any;
export declare function DatafileGetFileDict(index: number): string;
export declare function DatafileGetFloat(p0: any, p1: any): any;
export declare function DatafileGetHash(p0: any, p1: any): any;
export declare function DatafileGetInt(p0: any, p1: any): any;
export declare function DatafileGetNumChildren(p0: any, p1: any): any;
export declare function DatafileGetNumNodes(p0: any): any;
export declare function DatafileGetString(p0: any, p1: any): any;
export declare function DatafileGetVector(p0: any, p1: any): any;
export declare function DatafileHasLoadedFileData(p0: any): boolean;
export declare function DatafileHasValidFileData(p0: any): boolean;
export declare function DatafileRegisterQuery(p0: any, p1: any, p2: any): any;
export declare function DatafileSelectActiveFile(p0: any, p1: any): boolean;
export declare function DatafileUnload(p0: any): void;
export declare function DatafileWatchRequestId(id: number): void;
export declare function ObjectValueAddInteger(key: string, value: number): any;
export declare function ObjectValueGetArray(key: string): [any, any];
export declare function ObjectValueGetBoolean(key: string): [boolean, any];
export declare function ObjectValueGetFloat(key: string): [number, any];
export declare function ObjectValueGetInteger(key: string): [number, any];
export declare function ObjectValueGetObject(key: string): [any, any];
export declare function ObjectValueGetString(key: string): [string, any];
export declare function ObjectValueGetType(key: string): [number, any];
export declare function ObjectValueGetVector3(key: string): [[number, number, number], any];
// Hash functions
export declare function N_0x1c65cc931c0f946f(p0: any, p1: any, p2: any): void;
export declare function N_0x277251c161b4c3f4(p0: any, p1: any, p2: any): void;
export declare function N_0x3168ba5d6dece323(): void;
export declare function N_0x44b3a36933ac009c(p0: any, p1: any, p2: any): any;
export declare function N_0x4607d57c5f7d332a(p0: any): any;
export declare function N_0x4f9e3ed7617123ac(p0: any): any;
export declare function N_0x52fc26d2d2fc2987(p0: any, p1: any, p2: any): any;
export declare function N_0x603ac35fd4602c76(p0: any): any;
export declare function N_0x7681b677400c7071(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function N_0x7907969497ea92f5(p0: any): any;
export declare function N_0x790ec421078f5c4e(p0: any, p1: any, p2: any): any;
export declare function N_0x91ded5dd64bb2691(p0: any): void;
export declare function N_0x951327435dc5164b(p0: any, p1: any): any;
export declare function N_0x9f130129ebc31b34(p0: any, p1: any, p2: any): void;
export declare function N_0xa63cd20f19b961ab(p0: any, p1: any, p2: any): any;
export declare function N_0xb04b69cf277d15c0(p0: any): any;
export declare function N_0xb2b42607f7867576(p0: any, p1: any, p2: any): any;
export declare function N_0xbc0df006a4952c68(p0: any, p1: any, p2: any): void;
export declare function N_0xca56dd6ab7a39f64(p0: any): any;
export declare function N_0xd97d8d905f1562f2(p0: any): any;
export declare function N_0xe13634bb6baf0734(p0: any, p1: any): any;
export declare function N_0xe79c70e77e0973c7(p0: any, p1: any, p2: any, p3: any): any;
export declare function N_0xed4413cee1bf142c(p0: any): any;
