// Named functions
export declare function AddBloodPool(x: number, y: number, z: number, unused: boolean): void;
export declare function AddBloodPool2(x: number, y: number, z: number, p3: number, size: number, p5: number, permanent: boolean, p7: number, p8: boolean): void;
export declare function AddDecal(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any, p9: any, p10: any, p11: any, p12: any, p13: any, p14: any, p15: any, p16: any, p17: any, p18: any, p19: any, p20: any, p21: any): number;
export declare function AddEntityToEntityMask(entity: number, mask: number): void;
export declare function AddEntityToEntityMaskWithIntensity(entity: number, mask: number, intensity: number): void;
export declare function AddPetrolTrailDecalInfo(x: number, y: number, z: number, p3: number): void;
export declare function AddVegModifierSphere(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): any;
export declare function AllowPickupLightSync(pickupObject: Record<string, any>, allow: boolean): void;
export declare function AnimpostfxHasEventTriggeredByStackhash(effectNameHash: string | number, p1: number, p2: boolean): [boolean, boolean];
export declare function AnimpostfxIsPreloadingByStackhash(effectNameHash: string | number): boolean;
export declare function AnimpostfxIsRunning(effectName: string): boolean;
export declare function AnimpostfxPlay(effectName: string): void;
export declare function AnimpostfxPlayTimed(effectName: string, duration: number): void;
export declare function AnimpostfxStop(effectName: string): void;
export declare function AnimpostfxStopAll(): void;
export declare function AttachTvAudioToEntity(entity: number): void;
export declare function BeginTakeHighQualityPhoto(): boolean;
export declare function BlockPickupObjectLight(pickupObject: Record<string, any>, toggle: boolean): void;
export declare function BlockPickupPlacementLight(pickup: number, toggle: boolean): void;
export declare function CascadeShadowsClearShadowSampleType(): void;
export declare function CascadeShadowsEnableEntityTracker(toggle: boolean): void;
export declare function CascadeShadowsSetCascadeBounds(p0: any, p1: boolean, p2: number, p3: number, p4: number, p5: number, p6: boolean, p7: number): void;
export declare function CascadeShadowsSetShadowSampleType(type: string): void;
export declare function ClearTimecycleModifier(): void;
export declare function CreateBloodPoolsFromPed(ped: number, sizeX: number, sizeY: number, sizeZ: number): void;
export declare function CreateCheckpointWithNamehash(typeHash: string | number, posX1: number, posY1: number, posZ1: number, posX2: number, posY2: number, posZ2: number, radius: number, red: number, green: number, blue: number, alpha: number, reserved: number): number;
export declare function CreateSwatchTextureDict(slots: number): boolean;
export declare function CreateTrackedPoint(): number;
export declare function DeleteCheckpoint(checkpoint: number): void;
export declare function DestroySwatchTextureDict(): void;
export declare function DestroyTrackedPoint(point: number): void;
export declare function DisableEntitymask(): void;
export declare function DisableStaticVegModifier(p0: string | number): void;
export declare function DoesParticleFxLoopedExist(ptfxHandle: number): boolean;
export declare function DrawLightWithRange(posX: number, posY: number, posZ: number, colorR: number, colorG: number, colorB: number, range: number, intensity: number): void;
export declare function DrawLowQualityPhotoToPhone(p0: boolean, p1: boolean): void;
export declare function DrawMarker(type: string | number, posX: number, posY: number, posZ: number, dirX: number, dirY: number, dirZ: number, rotX: number, rotY: number, rotZ: number, scaleX: number, scaleY: number, scaleZ: number, red: number, green: number, blue: number, alpha: number, bobUpAndDown: boolean, faceCamera: boolean, p19: number, rotate: boolean, textureDict: string, textureName: string, drawOnEnts: boolean): void;
export declare function DrawRect(x: number, y: number, width: number, height: number, red: number, green: number, blue: number, alpha: number, p8: boolean, p9: boolean): void;
export declare function DrawSprite(textureDict: string, textureName: string, screenX: number, screenY: number, width: number, height: number, heading: number, red: number, green: number, blue: number, alpha: number, p11: boolean): void;
export declare function DrawTvChannel(xPos: number, yPos: number, xScale: number, yScale: number, rotation: number, red: number, green: number, blue: number, alpha: number): void;
export declare function EnableEntitymask(): void;
export declare function EnableMovieSubtitles(toggle: boolean): void;
export declare function EnableStaticVegModifier(p0: string | number): void;
export declare function EndPetrolTrailDecals(): void;
export declare function FreeMemoryForHighQualityPhoto(): void;
export declare function FreeMemoryForLowQualityPhoto(): void;
export declare function FreeMemoryForMissionCreatorPhoto(): void;
export declare function GenerateSwatchTexture(slotId: number, componentHash: string | number, p2: number, p3: boolean): void;
export declare function GenerateSwatchTextureDirectly(slot: number, p1: any): void;
export declare function GetCurrentNumberOfLocalPhotos(): number;
export declare function GetMaxNumberOfLocalPhotos(): number;
export declare function GetPhotoModeContrast(): number;
export declare function GetPhotoModeExposure(): number;
export declare function GetScreenCoordFromWorldCoord(worldX: number, worldY: number, worldZ: number): [boolean, number, number];
export declare function GetScreenResolution(): [number, number];
export declare function GetStatusOfLoadMissionCreatorPhoto(): [number, any];
export declare function GetStatusOfSaveHighQualityPhoto(): number;
export declare function GetStatusOfSortedListOperation(): any;
export declare function GetStatusOfTakeHighQualityPhoto(): number;
export declare function GetTimecycleModifierIndex(): number;
export declare function GetTimecycleTransitionModifierIndex(): number;
export declare function GetTogglePausedRenderphasesStatus(): boolean;
export declare function GetTvChannel(): number;
export declare function IsDecalAlive(decal: number): boolean;
export declare function IsStaticVegModifierEnabled(p0: string | number): boolean;
export declare function IsTrackedPointValid(point: number): boolean;
export declare function IsTrackedPointVisible(point: number): boolean;
export declare function IsTvPlaylistItemPlaying(videoCliphash: string | number): boolean;
export declare function LoadMissionCreatorPhoto(p1: any, p2: any, p3: any): [boolean, any];
export declare function RemoveDecal(decal: number): void;
export declare function RemoveDecalsFromObject(obj: Record<string, any>): void;
export declare function RemoveDecalsInRange(x: number, y: number, z: number, range: number): void;
export declare function RemoveEntityFromEntityMask(entity: number): void;
export declare function RemoveParticleFx(ptfxHandle: number, p1: boolean): void;
export declare function RemoveParticleFxFromEntity(entity: number): void;
export declare function RemoveParticleFxInRange(X: number, Y: number, Z: number, radius: number): void;
export declare function RemoveVegModifierSphere(p0: any, p1: any): void;
export declare function ResetParticleFxOverride(name: string): void;
export declare function ResetPausedRenderphases(): void;
export declare function SaveHighQualityPhoto(unused: number): boolean;
export declare function SetArtificialLightsState(state: boolean): void;
export declare function SetCheckpointRgba(checkpoint: number, red: number, green: number, blue: number, alpha: number): void;
export declare function SetCheckpointRgba2(checkpoint: number, red: number, green: number, blue: number, alpha: number): void;
export declare function SetExtraTimecycleModifierStrength(strength: number): void;
export declare function SetHidofEnvBlurParams(p0: boolean, p1: boolean, p2: number, p3: number, p4: number, p5: number): void;
export declare function SetLightsColorForEntity(entity: number, red: number, green: number, blue: number): void;
export declare function SetLightsIntensityForEntity(entity: number, intensity: number): void;
export declare function SetLightsTypeForEntity(entity: number, type: number): void;
export declare function SetParticleFxBulletImpactScale(scale: number): void;
export declare function SetParticleFxLoopedAlpha(ptfxHandle: number, alpha: number): void;
export declare function SetParticleFxLoopedColour(ptfxHandle: number, r: number, g: number, b: number, p4: boolean): void;
export declare function SetParticleFxLoopedEvolution(ptfxHandle: number, propertyName: string, amount: number, noNetwork: boolean): void;
export declare function SetParticleFxLoopedFarClipDist(ptfxHandle: number, range: number): void;
export declare function SetParticleFxLoopedOffsets(ptfxHandle: number, x: number, y: number, z: number, rotX: number, rotY: number, rotZ: number): void;
export declare function SetParticleFxLoopedScale(ptfxHandle: number, scale: number): void;
export declare function SetParticleFxNonLoopedAlpha(alpha: number): void;
export declare function SetParticleFxNonLoopedColour(r: number, g: number, b: number): void;
export declare function SetParticleFxNonLoopedEmitterScale(p0: number, p1: number, p2: number): void;
export declare function SetParticleFxOverride(oldAsset: string, newAsset: string): void;
export declare function SetPearlescentFxEnabled(object: Record<string, any>, toggle: boolean): void;
export declare function SetPickupLight(object: Record<string, any>, toggle: boolean): void;
export declare function SetScriptGfxDrawBehindPausemenu(toggle: boolean): void;
export declare function SetScriptGfxDrawOrder(drawOrder: number): void;
export declare function SetSnowCoverageType(type: number): void;
export declare function SetTimecycleModifier(modifierName: string): void;
export declare function SetTimecycleModifierStrength(strength: number): void;
export declare function SetTrackedPointInfo(point: number, x: number, y: number, z: number, radius: number): void;
export declare function SetTransitionTimecycleModifier(modifierName: string, transition: number): void;
export declare function SetTvAudioFrontend(toggle: boolean): void;
export declare function SetTvChannel(channel: number): void;
export declare function SetTvChannelPlaylist(tvChannel: number, playlistName: string, restart: boolean): void;
export declare function SetTvVolume(volume: number): void;
export declare function StartNetworkedParticleFxLoopedOnEntity(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any, p9: any, p10: any, p11: any): number;
export declare function StartNetworkedParticleFxLoopedOnEntityBone(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any, p9: any, p10: any, p11: any, p12: any): number;
export declare function StartNetworkedParticleFxNonLoopedAtCoord(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any, p9: any, p10: any): boolean;
export declare function StartNetworkedParticleFxNonLoopedOnEntity(effectName: string, entity: number, offsetX: number, offsetY: number, offsetZ: number, rotX: number, rotY: number, rotZ: number, scale: number, axisX: boolean, axisY: boolean, axisZ: boolean): boolean;
export declare function StartParticleFxLoopedAtCoord(effectName: string, x: number, y: number, z: number, xRot: number, yRot: number, zRot: number, scale: number, xAxis: boolean, yAxis: boolean, zAxis: boolean, p11: boolean): number;
export declare function StartParticleFxLoopedOnEntity(effectName: string, entity: number, xOffset: number, yOffset: number, zOffset: number, xRot: number, yRot: number, zRot: number, scale: number, xAxis: boolean, yAxis: boolean, zAxis: boolean): number;
export declare function StartParticleFxLoopedOnEntityBone(effectName: string, entity: number, xOffset: number, yOffset: number, zOffset: number, xRot: number, yRot: number, zRot: number, boneIndex: number, scale: number, xAxis: boolean, yAxis: boolean, zAxis: boolean): number;
export declare function StartParticleFxLoopedOnPedBone(effectName: string, ped: number, xOffset: number, yOffset: number, zOffset: number, xRot: number, yRot: number, zRot: number, boneIndex: number, scale: number, xAxis: boolean, yAxis: boolean, zAxis: boolean): number;
export declare function StartParticleFxNonLoopedAtCoord(effectName: string, xPos: number, yPos: number, zPos: number, xRot: number, yRot: number, zRot: number, scale: number, xAxis: boolean, yAxis: boolean, zAxis: boolean): number;
export declare function StartParticleFxNonLoopedOnEntity(effectName: string, entity: number, offsetX: number, offsetY: number, offsetZ: number, rotX: number, rotY: number, rotZ: number, scale: number, axisX: boolean, axisY: boolean, axisZ: boolean): boolean;
export declare function StartParticleFxNonLoopedOnPedBone(effectName: string, ped: number, offsetX: number, offsetY: number, offsetZ: number, rotX: number, rotY: number, rotZ: number, boneIndex: number, scale: number, axisX: boolean, axisY: boolean, axisZ: boolean): boolean;
export declare function StartParticleFxNonLoopedOnPedBone2(effectName: string, ped: number, offsetX: number, offsetY: number, offsetZ: number, rotX: number, rotY: number, rotZ: number, boneIndex: number, scale: number, axisX: boolean, axisY: boolean, axisZ: boolean): boolean;
export declare function StartPetrolTrailDecals(p0: any, p1: any): void;
export declare function StopParticleFxLooped(ptfxHandle: number, p1: boolean): void;
export declare function TogglePausedRenderphases(toggle: boolean): void;
export declare function UpdateLightsOnEntity(entity: number): void;
export declare function UseParticleFxAsset(name: string): void;
// Hash functions
export declare function N_0x085c5b61a0114f32(p0: any, p1: any): void;
export declare function N_0x0d5b19c34068fee7(p0: any): void;
export declare function N_0x10c1767b93257480(p0: any, p1: any, p2: any): void;
export declare function N_0x113857d66a9cabe6(p0: any): any;
export declare function N_0x13430d3d5a45f14b(p0: any): any;
export declare function N_0x1460b644397453eb(): void;
export declare function N_0x171c18e994c1a395(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function N_0x196d3acbeba4a44b(p0: any): void;
export declare function N_0x1a9f09ab458d49c6(p0: boolean): void;
export declare function N_0x1c6306e5bc25c29c(): void;
export declare function N_0x1ff8731be1dfc0c0(p0: any, p1: any): void;
export declare function N_0x21f00e08cbb5f37b(p0: any): void;
export declare function N_0x249cd6b7285536f2(p0: any, p1: any, p2: any): void;
export declare function N_0x25ca89b2a39dcc69(): any;
export declare function N_0x26dd2fb0a88cc412(effectName: string, effectName2: string, p2: any, p3: any): void;
export declare function N_0x2705d18c11b61046(p0: any): void;
export declare function N_0x27219300c36a8d40(p0: any, p1: any, p2: any, p3: any, p4: any): any;
export declare function N_0x285438c26c732f9d(): any;
export declare function N_0x297b72e2af094742(unk: number): void;
export declare function N_0x2a1625858887d4e6(p0: number): void;
export declare function N_0x2d4f9c852ce8a253(effectName: string): boolean;
export declare function N_0x32de2bffda43e62a(): void;
export declare function N_0x37d7bdba89f13959(effectName: string): void;
export declare function N_0x38d9d50f2085e9b3(effectNameHash: string | number): void;
export declare function N_0x3c61b52b00848c26(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function N_0x3da7a10583a4bec0(): boolean;
export declare function N_0x3e2fddbe435a8787(): void;
export declare function N_0x402e1a61d2587fcd(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): any;
export declare function N_0x4046493d2eeaca0e(): void;
export declare function N_0x41f88a85a579a61d(p0: any): void;
export declare function N_0x453d16d41fc51d3e(p0: any): void;
export declare function N_0x48fe0db54045b975(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): void;
export declare function N_0x494a9874f17a7d50(p0: any): boolean;
export declare function N_0x4bd66b4e3427689b(p0: any): void;
export declare function N_0x4c11ccacb7c02b6e(p0: any): any;
export declare function N_0x4fb67d172c4476f3(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0x503941f65dba24ec(p0: any): void;
export declare function N_0x519928df02eb5101(p0: any): void;
export declare function N_0x5199405eabfbd7f0(effectName: string): void;
export declare function N_0x53ed07bf368eda59(): void;
export declare function N_0x55285f885f662169(): void;
export declare function N_0x564837d4a9ede296(p0: any): void;
export declare function N_0x5ac6e0fa028369de(): void;
export declare function N_0x5c674eb487891f6b(): any;
export declare function N_0x5c9c3a466b3296a8(p0: any): any;
export declare function N_0x5cd6a2cce5087161(p0: any): void;
export declare function N_0x5d1c5d8e62e8ee1c(p0: any): any;
export declare function N_0x62b9f9a1272aed80(p0: any): void;
export declare function N_0x63011d0c7c6519e0(effectName: string, p1: number, red: number, green: number, blue: number, alpha: number): void;
export declare function N_0x67b0778c62e74423(p0: any): void;
export declare function N_0x6c03118e9e5c1a14(p0: any): void;
export declare function N_0x6e8eb45a4f4460eb(p0: any): void;
export declare function N_0x71845905bccde781(effectNameHash: string | number): void;
export declare function N_0x735762e8d7573e42(p0: any, p1: any, p2: any): void;
export declare function N_0x75d568607909333e(p0: any): void;
export declare function N_0x812c1563185c6fb2(): void;
export declare function N_0x815653a42c5abe76(): void;
export declare function N_0x842ccc9491ffcd9b(effectName: string): string | number;
export declare function N_0x86076ae35cbbe55f(): any;
export declare function N_0x8952e857696b8a79(p0: any): void;
export declare function N_0x8996fa6ad9fe4e90(p0: any): void;
export declare function N_0x8b3296278328b5eb(p0: any): void;
export declare function N_0x8dccc98dc0dbf9e4(p0: number): void;
export declare function N_0x8e6aff353c09652e(p0: any): void;
export declare function N_0x910e260aead855de(): void;
export declare function N_0x9229ed770975bd9e(): void;
export declare function N_0x94b261f1f35293e1(p0: any): void;
export declare function N_0x981c7d863980fa51(): void;
export declare function N_0x98a7cd5ea379a854(): void;
export declare function N_0x9937facbbf267244(p0: any): void;
export declare function N_0x9b8d5d4cb8af58b3(effectNameHash: string | number): void;
export declare function N_0x9d1b0b5066205692(): void;
export declare function N_0x9ddc222d85d5af2a(p0: any, p1: any): void;
export declare function N_0x9f158a49b0d84c3c(p0: any): void;
export declare function N_0x9f6d859c80708b26(p0: any, p1: any): void;
export declare function N_0xa04ef43030593abc(p0: any, p1: any): void;
export declare function N_0xa0f4d12d6042f6d5(p0: any, p1: any): void;
export declare function N_0xa15ccab8ad038291(p0: any, p1: any, p2: any, p3: any): any;
export declare function N_0xa1a86055792fb249(p0: any): void;
export declare function N_0xa201a3d0ac087c37(effectName: string): void;
export declare function N_0xa21af60c9f99ccc5(): void;
export declare function N_0xa2a51869bded733b(p0: any, p1: any): any;
export declare function N_0xa42edf1e88734a7e(): any;
export declare function N_0xad74c22a541ab987(effectName: string): void;
export declare function N_0xae7bf7ca9e4ba48d(p0: any): void;
export declare function N_0xaf4d239b8903fcbe(): void;
export declare function N_0xaf6e67d073d2dce2(): any;
export declare function N_0xb032c085d9a03907(): void;
export declare function N_0xb8c984c0d47f4f07(p0: any, p1: any, p2: any): void;
export declare function N_0xb958d97a0dfaa0c2(effectName: string): boolean;
export declare function N_0xb9c92616929cc25d(p0: any, p1: any): void;
export declare function N_0xbb6c707f20d955d4(p0: number): void;
export declare function N_0xbd3324281e8b9933(p0: any, p1: any, p2: any, p3: any): any;
export declare function N_0xbf2dd155b2adcd0a(effectName: string): boolean;
export declare function N_0xbfcb17895bb99e4e(p0: any, p1: any): void;
export declare function N_0xc06f2f45a73eabcd(p0: any): void;
export declare function N_0xc28f62ac9774fc1b(): any;
export declare function N_0xc2b8164c3be871a4(): void;
export declare function N_0xc332c91388f5580b(p0: any): void;
export declare function N_0xc37792a3f9c90771(): any;
export declare function N_0xc38b4952b728397a(p0: any, p1: any): void;
export declare function N_0xc489fe31ac726512(p0: any, p1: any): void;
export declare function N_0xc5cb91d65852ed7e(effectName: string): void;
export declare function N_0xc76fc4c2fc5f4405(effectNameHash: string | number): void;
export declare function N_0xc8d0611d9a0cf5d3(p0: any): void;
export declare function N_0xcab4dd2d5b2b7246(effectName: string, p1: number): void;
export declare function N_0xcc3b787e73e64160(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function N_0xcd284e2f6ac27ee9(p0: any): void;
export declare function N_0xd1031b83ac093bc7(p0: any): void;
export declare function N_0xd1472aff30c103d6(p0: any): void;
export declare function N_0xd543487a1f12828f(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0xd9bc98b55bcfaa9b(p0: any): void;
export declare function N_0xd9c24f53631f2372(p0: any, p1: any, p2: any): any;
export declare function N_0xdd9dc1ab63d513ce(p0: any, p1: any, p2: any): void;
export declare function N_0xdfce8ce9f3ebe93f(p0: any): void;
export declare function N_0xdfe332a5da6fe7c9(p0: any): any;
export declare function N_0xe63d68f455ca0b47(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): any;
export declare function N_0xe75cddebf618c8ff(effectNameHash: string | number): boolean;
export declare function N_0xe8a8378bf651079c(p0: any, p1: any, p2: any, p3: any, p4: any): any;
export declare function N_0xe92012611461a42a(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function N_0xeb48ce48eec41fd4(p0: any): void;
export declare function N_0xec3d8c228fe553d7(p0: any): any;
export declare function N_0xec3f7f24eeeb3ba3(): void;
export declare function N_0xeda5cbecf56e1386(effectNameHash: string | number): void;
export declare function N_0xeef83a759ae06a27(effectNameHash: string | number): boolean;
export declare function N_0xf2f543d48f319a3a(): void;
export declare function N_0xf3e039322bfbd4d8(effectNameHash: string | number): void;
export declare function N_0xf5793bb386e1ff9c(p0: any): void;
export declare function N_0xf5e45cb1cf965d2d(p0: any, p1: any, p2: any): void;
export declare function N_0xf972f0ab16dc5260(effectName: string, p1: number, p2: number): void;
export declare function N_0xfa91736933ab3d93(p0: any): void;
export declare function N_0xfb680a9b33d0edbe(p0: any): void;
export declare function N_0xfbf161fcfec8589e(effectName: string, p1: number, p2: boolean): [boolean, boolean];
export declare function N_0xfc9b53c072f418e0(): any;
export declare function N_0xfd05b1dde83749fa(p0: any): any;
export declare function N_0xfe7966df01452f32(p0: any, p1: any, p2: any): void;
export declare function N_0xff584f097c17fa8f(): boolean;
export declare function N_0xff8018c778349234(p0: any): void;
