// Named functions
export declare function ItemdatabaseCanEquipItemOnCategory(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseCreateItemCollection(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseDoesItemHaveTag(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseFilloutAcquireCost(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseFilloutBuyAwardAcquireCosts(p0: any, p1: any, p2: any, p3: any): any;
export declare function ItemdatabaseFilloutItemByName(p0: any, p1: any): any;
export declare function ItemdatabaseFilloutItemEffectIdInfo(p0: any, p1: any): any;
export declare function ItemdatabaseFilloutItemEffectIds(p0: any, p1: any): any;
export declare function ItemdatabaseFilloutItemInfo(p0: any, p1: any): any;
export declare function ItemdatabaseFilloutModifier(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseFilloutPriceModifierByKey(p0: any, p1: any): any;
export declare function ItemdatabaseFilloutSatchelData(p0: any, p1: any): any;
export declare function ItemdatabaseFilloutSellPrice(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseFilloutTagData(p0: any, p1: any, p2: any, p3: any): any;
export declare function ItemdatabaseFilloutUiData(p0: any, p1: any): any;
export declare function ItemdatabaseGetAcquireCost(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseGetAcquireCostsCount(p0: any): any;
export declare function ItemdatabaseGetBundleId(p0: any): any;
export declare function ItemdatabaseGetBundleItemCount(p0: any, p1: any): any;
export declare function ItemdatabaseGetBundleItemInfo(p0: any, p1: any, p2: any, p3: any): any;
export declare function ItemdatabaseGetFitsSlotCount(p0: any): any;
export declare function ItemdatabaseGetFitsSlotInfo(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseGetHasSlotCount(p0: any): any;
export declare function ItemdatabaseGetHasSlotInfo(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseGetItemPriceModifiers(p0: any, p1: any): any;
export declare function ItemdatabaseGetItemTagType(p0: any, p1: any): any;
export declare function ItemdatabaseGetModifiedPrice(p0: any, p1: any): any;
export declare function ItemdatabaseGetNumberOfModifiedPrices(p0: any): any;
export declare function ItemdatabaseGetNumberOfModifiers(p0: any): any;
export declare function ItemdatabaseGetShopInventoriesItemInfo(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseGetShopInventoriesItemInfoByKey(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseGetShopInventoriesItemsCount(p0: any): any;
export declare function ItemdatabaseGetShopInventoriesRequirementGroupInfo(p0: any, p1: any, p2: any, p3: any): any;
export declare function ItemdatabaseGetShopInventoriesRequirementInfo(p0: any, p1: any, p2: any, p3: any, p4: any): any;
export declare function ItemdatabaseGetShopLayoutInfo(p0: any, p1: any): any;
export declare function ItemdatabaseGetShopLayoutMenuInfoById(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseGetShopLayoutMenuInfoByIndex(p0: any, p1: any, p2: any, p3: any): any;
export declare function ItemdatabaseGetShopLayoutMenuPageKey(p0: any, p1: any, p2: any, p3: any): any;
export declare function ItemdatabaseGetShopLayoutPageInfoByKey(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseGetShopLayoutPageItemKey(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
export declare function ItemdatabaseGetShopLayoutRootMenuInfo(p0: any, p1: any, p2: any): any;
export declare function ItemdatabaseIsBuyableAwardValid(p0: any): any;
export declare function ItemdatabaseIsIntrinsicItem(p0: any): any;
export declare function ItemdatabaseIsKeyValid(p0: any, p1: any): any;
export declare function ItemdatabaseIsOverpoweredItem(p0: any): any;
export declare function ItemdatabaseIsShopKeyValid(p0: any): any;
export declare function ItemdatabaseIsShopLayoutKeyValid(p0: any): any;
export declare function ItemdatabaseLocalizationGetNumLabelTypes(p0: any): any;
export declare function ItemdatabaseLocalizationGetNumValues(p0: any, p1: any): any;
export declare function ItemdatabaseLocalizationGetType(p0: any, p1: any): any;
export declare function ItemdatabaseLocalizationGetValue(p0: any, p1: any, p2: any): any;
// Hash functions
export declare function N_0x121d2005dd64496b(p0: any, p1: any, p2: any): any;
export declare function N_0x12df9c58201dd19a(p0: any): any;
export declare function N_0x17721003a66c72bf(p0: any, p1: any, p2: any): any;
export declare function N_0x1fc25aeb5f76b38d(p0: any, p1: any, p2: any): any;
export declare function N_0x388088bff3681189(p0: any, p1: any): any;
export declare function N_0x3a0b667abff87f6e(p0: any, p1: any, p2: any): any;
export declare function N_0x3faa928a79591761(p0: any): any;
export declare function N_0x4308812a6e9ca62e(p0: any, p1: any): any;
export declare function N_0x48229ce0c7938237(p0: any): any;
export declare function N_0x74c3b1093728d263(p0: any, p1: any): any;
export declare function N_0x799fcd53358ed5fa(p0: any, p1: any): any;
export declare function N_0x7a35a72a692be9db(p0: any): any;
export declare function N_0x8750f69a720c2e41(p0: any, p1: any, p2: any): any;
export declare function N_0x8870895ba5ed9385(p0: any, p1: any, p2: any): any;
export declare function N_0x8d029948ca29409b(p0: any, p1: any, p2: any): any;
export declare function N_0x99c6ea66dfe73757(p0: any, p1: any, p2: any): any;
export declare function N_0xa97ee5e4589fcf5a(p0: any, p1: any): any;
export declare function N_0xaa29a5f13b2c20b2(p0: any, p1: any): any;
export declare function N_0xad73b614df26cf8a(p0: any, p1: any, p2: any, p3: any): any;
export declare function N_0xb542632693d53408(p0: any, p1: any, p2: any, p3: any): any;
export declare function N_0xc4146375d8a0b374(p0: any, p1: any, p2: any, p3: any): any;
export declare function N_0xcbb7b6edfa933ade(p0: any): any;
export declare function N_0xd076db9b96faadf1(p0: any, p1: any): any;
export declare function N_0xd389a2549c4efb30(p0: any): any;
export declare function N_0xdbeada0df5f9ab9f(p0: any, p1: any, p2: any): any;
export declare function N_0xdee7b3c76ed664be(p0: any, p1: any): any;
export declare function N_0xe81d0378a384e755(p0: any, p1: any): any;
export declare function N_0xef254f1a4c08b7e6(p0: any): any;
export declare function N_0xf27f01bbf5acd3f3(p0: any, p1: any, p2: any, p3: any): any;
export declare function N_0xf4452ce83118c738(p0: any, p1: any): any;
export declare function N_0xf540239f9937033b(p0: any, p1: any): any;
export declare function N_0xf8d09ef8ce61d7bf(p0: any, p1: any): any;
