// Named functions
export declare function ItemDatabaseCanEquipItemOnCategory(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseCreateItemCollection(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseDoesItemHaveTag(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseFilloutAcquireCost(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseFilloutBuyAwardAcquireCosts(p0: any, p1: any, p2: any, p3: any): any;
export declare function ItemDatabaseFilloutItemEffectsIdInfo(p0: any, p1: any): any;
export declare function ItemDatabaseFilloutItemEffectsIds(p0: any, p1: any): any;
export declare function ItemDatabaseFilloutItemInfo(p0: any, p1: any): any;
export declare function ItemDatabaseFilloutModifier(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseFilloutPriceModifierByKey(p0: any, p1: any): any;
export declare function ItemDatabaseFilloutSatchelData(p0: any, p1: any): any;
export declare function ItemDatabaseFilloutSellPrice(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseFilloutTagData(p0: any, p1: any, p2: any, p3: any): any;
export declare function ItemDatabaseFilloutUiData(p0: any, p1: any): any;
export declare function ItemDatabaseGetAcquireCost(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseGetAcquireCostsCount(p0: any): any;
export declare function ItemDatabaseGetBundleId(p0: any): any;
export declare function ItemDatabaseGetBundleItemCount(p0: any, p1: any): any;
export declare function ItemDatabaseGetBundleItemInfo(p0: any, p1: any, p2: any, p3: any): any;
export declare function ItemDatabaseGetFitsSlotCount(p0: any): any;
export declare function ItemDatabaseGetFitsSlotInfo(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseGetHasSlotCount(p0: any): any;
export declare function ItemDatabaseGetHasSlotInfo(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseGetItemPriceModifiers(p0: any, p1: any): any;
export declare function ItemDatabaseGetItemTagType(p0: any, p1: any): any;
export declare function ItemDatabaseGetModifiedPrice(p0: any, p1: any): any;
export declare function ItemDatabaseGetNumberOfModifiedPrices(p0: any): any;
export declare function ItemDatabaseGetNumberOfModifiers(p0: any): any;
export declare function ItemDatabaseGetShopInventoriesItemInfo(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseGetShopInventoriesItemInfoByKey(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseGetShopInventoriesItemsCount(p0: any): any;
export declare function ItemDatabaseGetShopInventoriesRequirementGroupInfo(p0: any, p1: any, p2: any, p3: any): any;
export declare function ItemDatabaseGetShopInventoriesRequirementInfo(p0: any, p1: any, p2: any, p3: any, p4: any): any;
export declare function ItemDatabaseGetShopLayoutInfo(p0: any, p1: any): any;
export declare function ItemDatabaseGetShopLayoutMenuInfoById(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseGetShopLayoutMenuInfoByIndex(p0: any, p1: any, p2: any, p3: any): any;
export declare function ItemDatabaseGetShopLayoutMenuPageKey(p0: any, p1: any, p2: any, p3: any): any;
export declare function ItemDatabaseGetShopLayoutPageInfoByKey(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseGetShopLayoutPageItemKey(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
export declare function ItemDatabaseGetShopLayoutRootMenuInfo(p0: any, p1: any, p2: any): any;
export declare function ItemDatabaseIsBuyAwardKeyValid(p0: any): any;
export declare function ItemDatabaseIsIntrinsicItem(p0: any): any;
export declare function ItemDatabaseIsKeyValid(p0: any, p1: any): any;
export declare function ItemDatabaseIsOverpoweredItem(p0: any): any;
export declare function ItemDatabaseIsShopKeyValid(p0: any): any;
export declare function ItemDatabaseIsShopLayoutKeyValid(p0: any): any;
export declare function ItemDatabaseLocalizationGetNumLabelTypes(p0: any): any;
export declare function ItemDatabaseLocalizationGetNumValues(p0: any, p1: any): any;
export declare function ItemDatabaseLocalizationGetType(p0: any, p1: any): any;
export declare function ItemDatabaseLocalizationGetValue(p0: any, p1: any, p2: any): any;
// Hash functions
export declare function N_0x121d2005dd64496b(p0: any, p1: any, p2: any): any;
export declare function N_0x12df9c58201dd19a(p0: any): any;
export declare function N_0x17721003a66c72bf(p0: any, p1: any, p2: any): any;
export declare function N_0x1fc25aeb5f76b38d(p0: any, p1: any, p2: any): any;
export declare function N_0x2a610bee7d341cc4(p0: any, p1: any): any;
export declare function N_0x388088bff3681189(p0: any, p1: any): any;
export declare function N_0x3a0b667abff87f6e(p0: any, p1: any, p2: any): any;
export declare function N_0x3faa928a79591761(p0: any): any;
export declare function N_0x4308812a6e9ca62e(p0: any, p1: any): any;
export declare function N_0x48229ce0c7938237(p0: any): any;
export declare function N_0x74c3b1093728d263(p0: any, p1: any): any;
export declare function N_0x799fcd53358ed5fa(p0: any, p1: any): any;
export declare function N_0x7a35a72a692be9db(p0: any): any;
export declare function N_0x8750f69a720c2e41(p0: any, p1: any, p2: any): any;
export declare function N_0x8870895ba5ed9385(p0: any, p1: any, p2: any): any;
export declare function N_0x8d029948ca29409b(p0: any, p1: any, p2: any): any;
export declare function N_0x99c6ea66dfe73757(p0: any, p1: any, p2: any): any;
export declare function N_0xa97ee5e4589fcf5a(p0: any, p1: any): any;
export declare function N_0xaa29a5f13b2c20b2(p0: any, p1: any): any;
export declare function N_0xad73b614df26cf8a(p0: any, p1: any, p2: any, p3: any): any;
export declare function N_0xb542632693d53408(p0: any, p1: any, p2: any, p3: any): any;
export declare function N_0xc4146375d8a0b374(p0: any, p1: any, p2: any, p3: any): any;
export declare function N_0xcbb7b6edfa933ade(p0: any): any;
export declare function N_0xd076db9b96faadf1(p0: any, p1: any): any;
export declare function N_0xd389a2549c4efb30(p0: any): any;
export declare function N_0xdbeada0df5f9ab9f(p0: any, p1: any, p2: any): any;
export declare function N_0xdee7b3c76ed664be(p0: any, p1: any): any;
export declare function N_0xe81d0378a384e755(p0: any, p1: any): any;
export declare function N_0xef254f1a4c08b7e6(p0: any): any;
export declare function N_0xf27f01bbf5acd3f3(p0: any, p1: any, p2: any, p3: any): any;
export declare function N_0xf4452ce83118c738(p0: any, p1: any): any;
export declare function N_0xf540239f9937033b(p0: any, p1: any): any;
export declare function N_0xf8d09ef8ce61d7bf(p0: any, p1: any): any;
