// Named functions
export declare function AddPointToGpsMultiRoute(x: number, y: number, z: number, p3: boolean): void;
export declare function AllowSonarBlips(toggle: boolean): void;
export declare function BlipAddForArea(blipHash: string | number, x: number, y: number, z: number, scaleX: number, scaleY: number, scaleZ: number, p7: number): number;
export declare function BlipAddForCoords(blipHash: string | number, x: number, y: number, z: number): number;
export declare function BlipAddForEntity(blipHash: string | number, entity: number): number;
export declare function BlipAddForPickupPlacement(blipHash: string | number, p1: any): number;
export declare function BlipAddForRadius(blipHash: string | number, x: number, y: number, z: number, radius: number): number;
export declare function BlipAddModifier(blip: number, modifierHash: string | number): boolean;
export declare function BlipRemoveModifier(blip: number, modifierHash: string | number): boolean;
export declare function BlipSetStyle(blip: number, styleHash: string | number): boolean;
export declare function ClearGpsCustomRoute(): void;
export declare function ClearGpsFlags(): void;
export declare function ClearGpsMultiRoute(): void;
export declare function ClearGpsPlayerWaypoint(): void;
export declare function DisplayRadar(toggle: boolean): void;
export declare function DoesBlipExist(blip: number): boolean;
export declare function DoesEntityHaveBlip(entity: number): boolean;
export declare function FindClosestGpsPosition(x: number, y: number, z: number): [boolean, [number, number, number]];
export declare function ForceSonarBlipsThisFrame(): any;
export declare function GetBlipCoords(blip: number): [number, number, number];
export declare function GetBlipFromEntity(entity: number): number;
export declare function GetMainPlayerBlipId(): number;
export declare function GetWaypointCoords(): [number, number, number];
export declare function HideActivePointsOfInterest(): void;
export declare function IsBlipAttachedToAnyEntity(blip: number): boolean;
export declare function IsBlipOnMinimap(blip: number): boolean;
export declare function IsWaypointActive(): boolean;
export declare function LockMinimapAngle(angle: number): void;
export declare function MapDiscoverySetEnabled(discoveryHash: string | number): void;
export declare function MapIsDiscoveryActive(discoveryHash: string | number): boolean;
export declare function RemoveBlip(): number;
export declare function ResetMinimapFow(hash: string | number): void;
export declare function RevealMinimapFow(hash: string | number): void;
export declare function SetBlipCoords(blip: number, posX: number, posY: number, posZ: number): void;
export declare function SetBlipFlashes(blip: number): [boolean, number, string | number];
export declare function SetBlipFlashTimer(blip: number, p1: number, p2: number): void;
export declare function SetBlipNameFromPlayerString(blip: number): const char;
export declare function SetBlipNameFromTextFile(blip: number): const char;
export declare function SetBlipNameToPlayerName(blip: number, player: number): void;
export declare function SetBlipRotation(blip: number, rotation: number): void;
export declare function SetBlipScale(blip: number, scale: number): void;
export declare function SetBlipSprite(blip: number, hash: string | number, p2: boolean): void;
export declare function SetFowUpdatePlayerOverride(toggle: boolean, p1: string | number): void;
export declare function SetGpsCustomRouteRender(p0: boolean, p1: number, p2: number): void;
export declare function SetGpsFlags(p0: number, p1: number): void;
export declare function SetGpsMultiRouteRender(toggle: boolean): void;
export declare function SetMinimapFowOverrideRevealScale(scale: number, p1: string | number): void;
export declare function SetMinimapFowRevealCoordinate(x: number, y: number, z: number, p3: string | number): void;
export declare function SetMinimapFowRevealVolume(volume: Volume, p1: string | number): void;
export declare function SetMinimapFowShouldUpdate(toggle: boolean, p1: string | number): void;
export declare function SetMinimapHideFow(toggle: boolean): void;
export declare function SetPausemapCoordsWithRadius(x: number, y: number, z: number, radius: number): void;
export declare function SetRadarAsExteriorThisFrame(): void;
export declare function SetRadarZoom(zoomLevel: number): void;
export declare function SetWaypointOff(): void;
export declare function ShowActivePointsOfInterest(): void;
export declare function StartGpsCustomRouteFromWaypointRecordingRoute(point: number, numPoints: number, colorNameHash: string | number, p4: boolean, p5: boolean): const char;
export declare function StartGpsMultiRoute(colorNameHash: string | number, p1: boolean, p2: boolean): void;
export declare function TriggerSonarBlip(typeHash: string | number, x: number, y: number, z: number): void;
export declare function TriggerSonarBlip2(typeHash: string | number, entity: number): void;
export declare function UnlockMinimapAngle(): void;
// Hash functions
export declare function N_0x01b928ca2e198b01(p0: any): any;
export declare function N_0x1392105da88bbffb(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function N_0x1726963e6049db53(p0: any): void;
export declare function N_0x250c75eb1728cc0d(blip: number): void;
export declare function N_0x3cb8859f04763c78(p0: any, p1: any): any;
export declare function N_0x3e593df9c2962ec6(p0: any): any;
export declare function N_0x44813684f72b563c(p0: any, p1: any): void;
export declare function N_0x563fcb6620523917(p0: any, p1: any): void;
export declare function N_0x6786d7afac3162b3(p0: any): void;
export declare function N_0x7563cbca99253d1a(p0: any, p1: any): void;
export declare function N_0x7c9f4cdf402ca82a(): void;
export declare function N_0x97f6f158cc5b5ca2(p0: any, p1: any): void;
export declare function N_0x9c113883487fd53c(p0: any, p1: any): void;
export declare function N_0xa657ec9dbc6cc900(hash: string | number): void;
export declare function N_0xa6ef0c54a3443e70(p0: any, p1: any): any;
export declare function N_0xbb68d4d3ca3de402(p0: any, p1: any): void;
export declare function N_0xbd62d98799a3daf0(p0: any, p1: any): any;
export declare function N_0xd3f58e9316b7fc2a(p0: any): void;
export declare function N_0xd8c7162ab2e2af45(p0: any): void;
export declare function N_0xdeede7c41742e011(p0: any): void;
export declare function N_0xe057fea9a22eb3ee(p0: any): void;
export declare function N_0xe38450dbcbc70e3d(p0: any, p1: any): any;
export declare function N_0xf08e42bfa46bdff8(p0: any, p1: any): any;
export declare function N_0xf47a1eb2a538a3a3(): any;
