// Named functions
export declare function AddLightPropSetToVehicle(vehicle: number, lightPropset: string | number): void;
export declare function CreatePropSet(hash: string | number, x: number, y: number, z: number, p4: number, p5: number, p6: number, p7: boolean, p8: boolean): PropSet;
export declare function CreatePropSet2(hash: string | number, x: number, y: number, z: number, p4: number, p5: number, p6: number, p7: boolean, p8: boolean): PropSet;
export declare function CreatePropSet4(hash: string | number, x: number, y: number, z: number, entity: number, p5: number, p6: boolean, p7: number, p8: boolean): PropSet;
export declare function CreatePropSetInstanceAttachedToEntity(hash: string | number, x: number, y: number, z: number, entity: number, p5: number, p6: boolean, p7: number, p8: boolean): PropSet;
export declare function DeletePropSet(propSet: PropSet, p1: boolean, p2: boolean): void;
export declare function DoesPropSetExist(propSet: PropSet): boolean;
export declare function DoesPropSetOfTypeExistNearCoords(propsetHash: string | number, x: number, y: number, z: number): boolean;
export declare function DoesVehicleHaveAnyLightPropSet(vehicle: number): boolean;
export declare function DoesVehicleHaveAnyPropSet(vehicle: number): boolean;
export declare function GetEntitiesFromPropSet(propSet: PropSet, itemSet: number, p2: any, p3: boolean, p4: boolean): number;
export declare function GetPropSetAtCoords(propsetHash: string | number, x: number, y: number, z: number): PropSet;
export declare function GetPropSetModel(propSet: PropSet): string | number;
export declare function GetVehicleLightPropSet(vehicle: number): PropSet;
export declare function GetVehiclePropSet(vehicle: number): PropSet;
export declare function GetVehiclePropSetHash(vehicle: number): string | number;
export declare function HasPropSetLoaded(hash: string | number): boolean;
export declare function HasPropSetLoaded2(hash: string | number): boolean;
export declare function IsPropSetFullyLoaded(propSet: PropSet): boolean;
export declare function IsPropSetVisible(propSet: PropSet): boolean;
export declare function ReleasePropSet(hash: string | number): boolean;
export declare function RemoveVehicleLightPropSets(vehicle: number): void;
export declare function RemoveVehiclePropSets(vehicle: number): void;
export declare function RequestPropSet(hash: string | number): boolean;
export declare function RequestPropSet2(hash: string | number): boolean;
export declare function SetPropSetAsNoLongerNeeded(propSet: PropSet): void;
export declare function SetPropSetVisible(propSet: PropSet, toggle: boolean): void;
// Hash functions
export declare function N_0x0790473eee1977d3(p0: any): any;
export declare function N_0x155b2fbe72d7d1d0(p0: any): any;
export declare function N_0x58e0b01d45ca7357(p0: any): void;
export declare function N_0x7264f9ca87a9830b(p0: any): any;
export declare function N_0x75f90e4051cc084c(p0: any, p1: any): void;
export declare function N_0x8f3333f0a6900b3c(p0: any, p1: any): any;
export declare function N_0xc1ab7eefd3e6ee49(p0: any, p1: any): void;
export declare function N_0xc4b67ef3fd65622d(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): void;
export declare function N_0xcfc0bd09bb1b73ff(p0: any): any;
export declare function N_0xd80faf919a2e56ea(p0: any, p1: any): void;
