// Named functions
export declare function IsScInboxValid(p0: number): boolean;
export declare function ScInboxGetTotalNumMessages(): number;
export declare function ScInboxMessageGetDataInt(p0: number): [boolean, const char, number];
export declare function ScInboxMessageGetDataString(p0: number, out: string): [boolean, const char];
export declare function ScInboxMessageGetString(p0: number): const char;
export declare function ScInboxMessageInit(p0: number): string | number;
export declare function ScInboxMessagePop(p0: number): boolean;
export declare function ScPresenceAttrSetFloat(attrHash: string | number, value: number): boolean;
export declare function ScPresenceAttrSetFloatEx(value: number, p2: boolean): [boolean, const char];
export declare function ScPresenceAttrSetIntEx(value: number, p2: boolean): [boolean, const char];
export declare function ScPresenceAttrSetStringEx(p2: boolean): [boolean, const char, const char];
export declare function ScProfanityCheckString(): [boolean, const char, number];
export declare function ScProfanityGetCheckIsPending(token: number): boolean;
export declare function ScProfanityGetCheckIsValid(token: number): boolean;
export declare function ScProfanityGetStringPassed(token: number): boolean;
export declare function ScProfanityGetStringStatus(token: number): number;
// Hash functions
export declare function N_0x03c03abbabbef752(): any;
export declare function N_0x049d2196d9d11184(): boolean;
export declare function N_0x060bbad634c2b44b(): any;
export declare function N_0x09937eb0cebc2f9f(): any;
export declare function N_0x11ea52cad1b55910(): boolean;
export declare function N_0x1bdb56db258f052d(): any;
export declare function N_0x3519cc3525319a96(): any;
export declare function N_0x62b384fefde06817(): any;
export declare function N_0x7c981de05a7403a0(): boolean;
export declare function N_0x85ea0bec7b1f7622(): any;
export declare function N_0x89d9bde7334b110f(): any;
export declare function N_0x91c9e2a0f9dd6dd4(): any;
export declare function N_0x9f6dcd0c939c71e9(): any;
export declare function N_0xb4411d4d6b81438e(): any;
export declare function N_0xc8fc3b2432e8229d(): any;
export declare function N_0xcbf743c984695cf3(): any;
export declare function N_0xd635df6baa5a6017(): any;
