// Named functions
export declare function ChalAchievementGetProgressInt(p0: string | number, p1: string | number): number;
export declare function ChalAchievementIsComplete(p0: string | number, p1: string | number): boolean;
export declare function ChalAddGoalProgressFloat(chalHash: string | number, goalHash: string | number, value: number): void;
export declare function ChalAddGoalProgressFloatByScoreId(p0: string | number, value: number): void;
export declare function ChalAddGoalProgressInt(chalHash: string | number, goalHash: string | number, value: number): void;
export declare function ChalAddGoalProgressIntByScoreId(p0: string | number, value: number): void;
export declare function ChalGetMaxRanks(chalHash: string | number): number;
export declare function ChalGetNumRanksCompleted(chalHash: string | number): number;
export declare function ChalIsGoalActive(chalHash: string | number, goalHash: string | number): boolean;
export declare function ChalMissionAddGoalProgressInt(missionHash: string | number, goalHash: string | number, value: number): void;
export declare function ChalMissionGetNumGoals(missionHash: string | number): number;
export declare function ChalMissionGetNumGoalsComplete(missionHash: string | number): number;
export declare function ChalMissionIsGoalComplete(missionHash: string | number, goalHash: string | number): boolean;
export declare function ChalNetStartChal(chalHash: string | number): void;
export declare function ChalNetStartGoal(chalHash: string | number, goalHash: string | number): void;
export declare function ChalNetStopChal(chalHash: string | number): void;
export declare function ChalNetStopGoal(chalHash: string | number, goalHash: string | number): void;
export declare function ChalSetGoalProgressInt(chalHash: string | number, goalHash: string | number, value: number): void;
export declare function StatIdGetBool(): [boolean, any, boolean];
export declare function StatIdGetDate(): [boolean, any, any];
export declare function StatIdGetFloat(): [boolean, any, number];
export declare function StatIdGetInt(): [boolean, any, number];
export declare function StatIdIncrementFloat(value: number): any;
export declare function StatIdIncrementInt(value: number): any;
export declare function StatIdIsValid(): [boolean, any];
export declare function StatIdSetBool(value: boolean, p2: boolean): [boolean, any];
export declare function StatIdSetDate(p2: boolean): [boolean, any, any];
export declare function StatIdSetFloat(value: number, p2: boolean): [boolean, any];
export declare function StatIdSetGxtLabel(label: string, p2: boolean): [boolean, any];
export declare function StatIdSetInt(value: number, p2: boolean): [boolean, any];
export declare function StatIdSetToPosseId(): any;
export declare function StatPhotographTaken(itemset: number): void;
export declare function WeeklyCollectibleGetItemInSet(chalHash: string | number, setIndex: number, itemIndex: number): [boolean, string | number, number];
export declare function WeeklyCollectibleGetItemSetBuyAward(chalHash: string | number, index: number): string | number;
export declare function WeeklyCollectibleGetItemSetLabel(chalHash: string | number, index: number): string | number;
export declare function WeeklyCollectibleGetNumItemsInSet(chalHash: string | number, index: number): number;
export declare function WeeklyCollectibleGetNumSets(chalHash: string | number): number;
// Hash functions
export declare function N_0x01f4d242765c6b24(p0: any): any;
export declare function N_0x025e98e317652cdd(p0: any): void;
export declare function N_0x0fee2561120f3333(p0: any): void;
export declare function N_0x1e7384ab5d4f4581(p0: any): any;
export declare function N_0x218f7710a139d012(): void;
export declare function N_0x262ef7cf49cf1eb9(p0: any): void;
export declare function N_0x302e71c1d9ee75b9(p0: any, p1: any, p2: any): any;
export declare function N_0x378d3b1b11d9385b(p0: any): void;
export declare function N_0x3aeabae3f3c7600c(): any;
export declare function N_0x3eb2791a1fbc8a42(p0: any, p1: any): void;
export declare function N_0x3f6fd87d2030adc6(): any;
export declare function N_0x4dac398297981b87(p0: any): any;
export declare function N_0x4e463a3cdefffe96(): void;
export declare function N_0x4f2d5fa23db992de(): void;
export declare function N_0x4fcbcc0584cd08e9(p0: any): void;
export declare function N_0x5420d398a42917fc(p0: any, p1: any): any;
export declare function N_0x6123e2832c34243d(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function N_0x6b1044fdc2b09101(p0: any, p1: any): void;
export declare function N_0x7c2abf6e556b21fc(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0x8312f09c56149a8a(p0: any): void;
export declare function N_0x831bf01c56149a8a(p0: any): void;
export declare function N_0x8ba3d7b1e83ef803(p0: any): any;
export declare function N_0x8c889e4cbb4b2356(p0: any, p1: any): void;
export declare function N_0x90e9a5dadbabc918(p0: any): void;
export declare function N_0x91a4f58e01ed5e4c(p0: any, p1: any): void;
export declare function N_0x99230691875fc218(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function N_0x9d0f5d2e1951cd84(): any;
export declare function N_0xa2e2bea4e83f6270(p0: any): any;
export declare function N_0xa59590050f80ff2e(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0xb112b9262ec29c20(p0: any, p1: any): any;
export declare function N_0xb22f05732f72f70c(p0: any): void;
export declare function N_0xb2a38826e5886e83(p0: any, p1: any): void;
export declare function N_0xb5e2eda2135e0fa1(p0: any, p1: any, p2: any): any;
export declare function N_0xbd861ae8a5181ed7(p0: any, p1: any): void;
export declare function N_0xbe66b26b6529e943(p0: any, p1: any, p2: any): void;
export declare function N_0xca1f0b5103936891(p0: any): any;
export declare function N_0xca41e86545413b5b(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): void;
export declare function N_0xcd0d69c65bb0e8b9(p0: any): void;
export declare function N_0xd5910ecf81a2278c(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0xd64dbc8b0424135f(p0: any, p1: any): void;
export declare function N_0xda26263c07cce9c2(p0: any): void;
export declare function N_0xda26263c87cce9c1(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0xddbd560745b1ee98(p0: any, p1: any, p2: any): any;
export declare function N_0xdf95df488a645ce7(): void;
export declare function N_0xe141f6b40b1e3683(p0: any, p1: any): void;
export declare function N_0xe5a680a5d8b1f687(p0: any): void;
export declare function N_0xf21a5d66874fcedd(p0: any, p1: any, p2: any): void;
export declare function N_0xf2b5abde09958689(p0: any, p1: any, p2: any): void;
export declare function N_0xf8181b5ef156862c(p0: any): void;
