// Named functions
export declare function AnalyticsPlaytimeFreemodeEnd(): void;
export declare function AnalyticsPlaytimeFreemodeStart(): void;
export declare function TelemetryAnimalSkinned(type: string | number): any;
export declare function TelemetryBountyTarget(): any;
export declare function TelemetryCampCreated(p0: any): void;
export declare function TelemetryCampDonate(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any): void;
export declare function TelemetryCampSupplies(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function TelemetryCharCreator(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): void;
export declare function TelemetryCollect(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): void;
export declare function TelemetryCoupon(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): void;
export declare function TelemetryCraftItem(p0: any, p1: any, p2: any, p3: any): void;
export declare function TelemetryCreateUuid(): [boolean, any];
export declare function TelemetryCustom(): any;
export declare function TelemetryDefensive(p0: any, p1: any, p2: any): void;
export declare function TelemetryFastTravel(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function TelemetryGameProgress(p0: any, p1: any): void;
export declare function TelemetryGangShares(p0: any, p1: any, p2: any, p3: any): void;
export declare function TelemetryGoldStore(p0: any, p1: any, p2: any, p3: any): void;
export declare function TelemetryGunLocker(): void;
export declare function TelemetryHerbPicked(p0: any): void;
export declare function TelemetryHonor(p0: any, p1: any): void;
export declare function TelemetryHubNavigation(p0: any, p1: any, p2: any, p3: any): void;
export declare function TelemetryIntroSkip(p0: any, p1: any, p2: any): void;
export declare function TelemetryLoot(p0: any, p1: any, p2: any, p3: any): void;
export declare function TelemetryMatchOver(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function TelemetryMatchQueue(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): void;
export declare function TelemetryMenuNavigation(p0: any, p1: any, p2: any, p3: any): void;
export declare function TelemetryMissionCheckpoint(p0: any, p1: any, p2: any): void;
export declare function TelemetryMissionIloOption(p0: any, p1: any): void;
export declare function TelemetryMissionOver(p0: any, p1: any): void;
export declare function TelemetryMissionStarted(p0: any, p1: any, p2: any, p3: any): void;
export declare function TelemetryMoonshineBrew(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any, p9: any, p10: any): void;
export declare function TelemetryNetCamp(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): void;
export declare function TelemetryNotoriety(p0: any, p1: any, p2: any, p3: any): void;
export declare function TelemetryParleyFeud(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function TelemetryPersonalVehicleMount(p0: any, p1: any, p2: any, p3: any): void;
export declare function TelemetryPhoto(p0: any, p1: any, p2: any, p3: any): void;
export declare function TelemetryPhotoCam(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any): void;
export declare function TelemetryPlayerMenuPin(p0: any, p1: any, p2: any, p3: any): void;
export declare function TelemetryPlayerSpawned(ped: number): void;
export declare function TelemetryPokerOver(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any, p9: any): void;
export declare function TelemetryPrison(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): void;
export declare function TelemetryRoleBounty(p0: any): void;
export declare function TelemetryRoleCollector(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): void;
export declare function TelemetryRoleMoonshiner(p0: any, p1: any): void;
export declare function TelemetryRoleNaturalist(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any, p9: any): void;
export declare function TelemetryRoleTokenTransaction(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): void;
export declare function TelemetryRoleTrader(p0: any, p1: any): void;
export declare function TelemetrySample(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function TelemetryShopCutscene(p0: any, p1: any, p2: any, p3: any): void;
export declare function TelemetryShopExit(p0: any, p1: any): void;
export declare function TelemetryShopPurchase(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function TelemetryShopSell(p0: any, p1: any, p2: any, p3: any, p4: any): void;
// Hash functions
export declare function N_0x16b23d4f7a1f50d9(p0: any, p1: any, p2: any): void;
export declare function N_0x2c24af8eeeef8a55(p0: any, p1: any, p2: any): void;
export declare function N_0x3145044f3990d321(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): void;
export declare function N_0x317d9c9560529cc2(p0: any): void;
export declare function N_0x32d5898c4898cd95(): void;
export declare function N_0x330029e121380ceb(): any;
export declare function N_0x37aa282163b0d2c4(p0: any, p1: any): void;
export declare function N_0x6571e4327390ec0b(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): void;
export declare function N_0x775b2ed944e44973(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): void;
export declare function N_0x7e002a36aefcfb55(): void;
export declare function N_0x80a02d9f948a8bca(p0: any, p1: any): any;
export declare function N_0x9bee018a63fffad9(p0: any): void;
export declare function N_0xc3adf4880784fa9c(p0: any): void;
export declare function N_0xca9e42f437625a85(p0: any, p1: any, p2: any): void;
export declare function N_0xcd6f8a0335d821f9(p0: any): void;
export declare function N_0xe67af24c5a3b6058(p0: any, p1: any, p2: any): void;
export declare function N_0xec0bd8736dcaf841(p0: any): void;
export declare function N_0xecd67e9fa677cccf(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0xef3c68f56bad7b69(p0: any, p1: any): void;
export declare function N_0xf0d54e0651dd7e07(): void;
export declare function N_0xf184b3ece36219cf(p0: any, p1: any): any;
export declare function N_0xf5ead898ef387e73(p0: any): void;
export declare function N_0xf620f47b4f4a78c4(p0: any, p1: any): void;
export declare function N_0xf9f14080d80937bd(p0: any): void;
