// Named functions
export declare function AddRoadNodeSpeedZone(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any, p9: any, p10: any): number;
export declare function AreAnyVehicleSeatsFree(vehicle: number): boolean;
export declare function BreakOffVehicleWheel(vehicle: number, wheelIndex: number): number;
export declare function BringVehicleToHalt(vehicle: number, distance: number, duration: number, unknown: boolean): void;
export declare function CanAnchorBoatHere(vehicle: number): boolean;
export declare function CanShuffleSeat(vehicle: number, seatIndex: number): boolean;
export declare function ClearLastDrivenVehicle(): void;
export declare function CopyVehicleDamages(sourceVehicle: number, targetVehicle: number): void;
export declare function CreateDraftVehicle(modelHash: string | number, x: number, y: number, z: number, heading: number, isNetwork: boolean, bScriptHostVeh: boolean, p7: boolean, numHorses: number, p9: boolean): number;
export declare function CreateMissionTrain(configHash: string | number, x: number, y: number, z: number, p4: boolean, passengers: boolean, p6: boolean, p7: boolean): number;
export declare function CreateVehicle(modelHash: string | number, x: number, y: number, z: number, heading: number, isNetwork: boolean, bScriptHostVeh: boolean, p7: boolean, p8: boolean): number;
export declare function DeleteAllTrains(): void;
export declare function DeleteMissionTrain(): number;
export declare function DeleteVehicle(): number;
export declare function DisableVehicleWeapon(disabled: boolean, weaponHash: string | number, vehicle: number, owner: number): void;
export declare function DoesExtraExist(vehicle: number, extraId: number): boolean;
export declare function ExplodeVehicle(vehicle: number, isAudible: boolean, isInvisible: boolean, p3: any): void;
export declare function ForcePlaybackRecordedVehicleUpdate(vehicle: number, p1: boolean): void;
export declare function GetBreakableVehicleLockObject(vehicle: number, index: number): Record<string, any>;
export declare function GetBreakableVehicleLocksState(vehicle: number): number;
export declare function GetClosestVehicle(x: number, y: number, z: number, radius: number, modelHash: string | number, flags: number): number;
export declare function GetDraftAnimalCount(vehicle: number): [boolean, number, number];
export declare function GetDriverOfVehicle(vehicle: number): number;
export declare function GetLastDrivenVehicle(): number;
export declare function GetLastPedInVehicleSeat(vehicle: number, seatIndex: number): number;
export declare function GetNearestTrainTrackPosition(x: number, y: number, z: number): [number, number, number];
export declare function GetNumBreakableVehicleLockObjects(vehicle: number): number;
export declare function GetPedInDraftSeat(vehicle: number, seatIndex: number): number;
export declare function GetPedInVehicleSeat(vehicle: number, seatIndex: number): number;
export declare function GetPositionOfVehicleRecordingAtTime(recording: number, time: number, script: string): [number, number, number];
export declare function GetRotationOfVehicleRecordingAtTime(recording: number, time: number, script: string): [number, number, number];
export declare function GetRowingOars(vehicle: number): [number, number];
export declare function GetTimePositionInRecording(vehicle: number): number;
export declare function GetTrainCarriage(train: number, trailerNumber: number): number;
export declare function GetVehicleBodyHealth(vehicle: number): number;
export declare function GetVehicleDoorLockStatus(vehicle: number): number;
export declare function GetVehicleDoorsLockedForPlayer(vehicle: number, player: number): boolean;
export declare function GetVehicleDoorsLockedForTeam(vehicle: number, team: number): boolean;
export declare function GetVehicleEngineHealth(vehicle: number): number;
export declare function GetVehicleEstimatedMaxSpeed(vehicle: number): number;
export declare function GetVehicleLivery(vehicle: number): number;
export declare function GetVehicleMaxNumberOfPassengers(vehicle: number): number;
export declare function GetVehicleModelNumberOfSeats(modelHash: string | number): number;
export declare function GetVehicleNumberOfPassengers(vehicle: number): number;
export declare function GetVehicleOwner(vehicle: number): number;
export declare function GetVehiclePetrolTankHealth(vehicle: number): number;
export declare function GetVehicleTint(vehicle: number): number;
export declare function GetVehicleTrailerVehicle(vehicle: number): [boolean, number];
export declare function GetVehicleTurretSeat(vehicle: number): [boolean, number];
export declare function HasVehicleAssetLoaded(vehicleAsset: number): boolean;
export declare function HasVehicleRecordingBeenLoaded(recording: number, script: string): boolean;
export declare function InstantlyFillVehiclePopulation(): void;
export declare function IsAnyVehicleNearPoint(x: number, y: number, z: number, radius: number): boolean;
export declare function IsDraftVehicle(vehicle: number): boolean;
export declare function IsPedExclusiveDriverOfVehicle(ped: number, vehicle: number): [boolean, number];
export declare function IsPlaybackGoingOnForVehicle(vehicle: number): boolean;
export declare function IsPlaybackUsingAiGoingOnForVehicle(vehicle: number): boolean;
export declare function IsSeatWarpOnly(vehicle: number, seatIndex: number): boolean;
export declare function IsThisModelABoat(model: string | number): boolean;
export declare function IsThisModelATrain(model: string | number): boolean;
export declare function IsVehicleDoorBroken(vehicle: number, doorIndex: number): boolean;
export declare function IsVehicleDoorFullyOpen(vehicle: number, doorIndex: number): boolean;
export declare function IsVehicleDriveable(vehicle: number, p1: boolean, p2: boolean): boolean;
export declare function IsVehicleExtraTurnedOn(vehicle: number, extraId: number): boolean;
export declare function IsVehicleInBurnout(vehicle: number): boolean;
export declare function IsVehicleModel(vehicle: number, model: string | number): boolean;
export declare function IsVehicleOnAllWheels(vehicle: number): boolean;
export declare function IsVehicleSeatFree(vehicle: number, seatIndex: number): boolean;
export declare function IsVehicleStopped(vehicle: number): boolean;
export declare function IsVehicleStuckTimerUp(vehicle: number, p1: number, p2: number): boolean;
export declare function IsVehicleVisible(vehicle: number): boolean;
export declare function IsVehicleWrecked(vehicle: number): boolean;
export declare function ModifyVehicleTopSpeed(vehicle: number, value: number): void;
export declare function RemoveRoadNodeSpeedZone(speedzone: number): boolean;
export declare function RemoveVehicleAsset(vehicleAsset: number): void;
export declare function RemoveVehicleRecording(p0: any): any;
export declare function RemoveVehiclesFromGeneratorsInArea(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): void;
export declare function RemoveVehicleWindow(vehicle: number, windowIndex: number): void;
export declare function RequestVehicleAsset(vehicleHash: string | number, vehicleAsset: number): void;
export declare function RequestVehicleHighDetailModel(vehicle: number): void;
export declare function RequestVehicleRecording(recording: number, script: string): void;
export declare function ResetVehicleStuckTimer(vehicle: number, nullAttributes: number): void;
export declare function SetAllVehicleGeneratorsActive(): void;
export declare function SetAllVehicleGeneratorsActiveInArea(x1: number, y1: number, z1: number, x2: number, y2: number, z2: number, p6: boolean, p7: boolean): void;
export declare function SetBoatAnchor(vehicle: number, toggle: boolean): void;
export declare function SetBoatAnchorBuoyancyCoefficient(vehicle: number, value: number): void;
export declare function SetBoatFrozenWhenAnchored(p0: any, p1: any, p2: any): void;
export declare function SetBoatSinksWhenWrecked(vehicle: number, toggle: boolean): void;
export declare function SetBreakableVehicleLocksUnbreakable(vehicle: number, toggle: boolean): void;
export declare function SetDisableRandomTrainsThisFrame(toggle: boolean): void;
export declare function SetDisableVehicleEngineFires(vehicle: number, p1: boolean): void;
export declare function SetDisableVehiclePetrolTankDamage(vehicle: number, toggle: boolean): void;
export declare function SetDisableVehiclePetrolTankFires(vehicle: number, toggle: boolean): void;
export declare function SetDraftVehicleDesiredSpeed(vehicle: number, speed: number): void;
export declare function SetEnableVehicleSlipstreaming(p0: boolean): void;
export declare function SetForceHdVehicle(vehicle: number, toggle: boolean): void;
export declare function SetMissionTrainAsNoLongerNeeded(p1: boolean): number;
export declare function SetMissionTrainCoords(train: number, x: number, y: number, z: number): void;
export declare function SetParkedVehicleDensityMultiplierThisFrame(multiplier: number): void;
export declare function SetPedOwnsVehicle(ped: number, vehicle: number): void;
export declare function SetPlaybackSpeed(vehicle: number, speed: number): void;
export declare function SetRandomBoats(toggle: boolean): void;
export declare function SetRandomTrains(toggle: boolean): void;
export declare function SetRandomVehicleDensityMultiplierThisFrame(multiplier: number): void;
export declare function SetTrainCruiseSpeed(train: number, speed: number): void;
export declare function SetTrainMaxSpeed(train: number, speed: number): void;
export declare function SetTrainOffsetFromStation(train: number, offset: number): void;
export declare function SetTrainSpeed(train: number, speed: number): void;
export declare function SetTrainStopsForStations(train: number, toggle: boolean): void;
export declare function SetVehicleAllowNoPassengersLockon(veh: number, toggle: boolean): void;
export declare function SetVehicleAutomaticallyAttaches(vehicle: number, p1: boolean, p2: any): any;
export declare function SetVehicleBodyHealth(vehicle: number, value: number): void;
export declare function SetVehicleCanBeTargetted(vehicle: number, state: boolean): void;
export declare function SetVehicleCanBeUsedByFleeingPeds(vehicle: number, toggle: boolean): void;
export declare function SetVehicleCanBeVisiblyDamaged(vehicle: number, state: boolean): void;
export declare function SetVehicleCanBreak(vehicle: number, toggle: boolean): void;
export declare function SetVehicleDamage(vehicle: number, xOffset: number, yOffset: number, zOffset: number, damage: number, radius: number, p6: boolean): void;
export declare function SetVehicleDensityMultiplierThisFrame(multiplier: number): void;
export declare function SetVehicleDirtLevel(vehicle: number, dirtLevel: number): void;
export declare function SetVehicleDirtLevel2(vehicle: number, dirtLevel: number): void;
export declare function SetVehicleDoorBroken(vehicle: number, doorIndex: number, deleteDoor: boolean): void;
export declare function SetVehicleDoorCanBreak(vehicle: number, doorIndex: number, isBreakable: boolean): void;
export declare function SetVehicleDoorControl(vehicle: number, doorIndex: number, speed: number, angle: number): void;
export declare function SetVehicleDoorLatched(vehicle: number, doorIndex: number, p2: boolean, p3: boolean, p4: boolean): void;
export declare function SetVehicleDoorOpen(vehicle: number, doorIndex: number, loose: boolean, openInstantly: boolean): void;
export declare function SetVehicleDoorShut(vehicle: number, doorIndex: number, closeInstantly: boolean): void;
export declare function SetVehicleDoorsLocked(vehicle: number, doorLockStatus: number): void;
export declare function SetVehicleDoorsLockedForAllPlayers(vehicle: number, toggle: boolean): void;
export declare function SetVehicleDoorsLockedForPlayer(vehicle: number, player: number, toggle: boolean): void;
export declare function SetVehicleDoorsLockedForTeam(vehicle: number, team: number, toggle: boolean): void;
export declare function SetVehicleDoorsShut(vehicle: number, closeInstantly: boolean): void;
export declare function SetVehicleDoorsToOpenAtAnyDistance(vehicle: number, toggle: boolean): void;
export declare function SetVehicleEngineCanDegrade(vehicle: number, toggle: boolean): void;
export declare function SetVehicleEngineHealth(vehicle: number, health: number): void;
export declare function SetVehicleEngineOn(vehicle: number, value: boolean, instantly: boolean): void;
export declare function SetVehicleExclusiveDriver(vehicle: number, ped: number, index: number): void;
export declare function SetVehicleExplodesOnHighExplosionDamage(vehicle: number, toggle: boolean): void;
export declare function SetVehicleExtra(vehicle: number, extraId: number, disable: boolean): void;
export declare function SetVehicleFixed(vehicle: number): void;
export declare function SetVehicleForwardSpeed(vehicle: number, speed: number): void;
export declare function SetVehicleHandbrake(vehicle: number, toggle: boolean): void;
export declare function SetVehicleHasBeenOwnedByPlayer(vehicle: number, owned: boolean): void;
export declare function SetVehicleHasStrongAxles(vehicle: number, toggle: boolean): void;
export declare function SetVehicleHasUnbreakableLights(vehicle: number, p1: boolean): void;
export declare function SetVehicleInactiveDuringPlayback(vehicle: number, toggle: boolean): void;
export declare function SetVehicleIndividualDoorsLocked(vehicle: number, doorIndex: number, doorLockStatus: number): void;
export declare function SetVehicleIsConsideredByPlayer(vehicle: number, toggle: boolean): void;
export declare function SetVehicleIsStolen(vehicle: number, isStolen: boolean): void;
export declare function SetVehicleJetEngineOn(vehicle: number, toggle: boolean): void;
export declare function SetVehicleLights(vehicle: number, state: number): void;
export declare function SetVehicleLivery(vehicle: number, liveryIndex: number): void;
export declare function SetVehicleLodLevel(vehicle: number, lodLevel: number): void;
export declare function SetVehicleLodMultiplier(vehicle: number, multiplier: number): void;
export declare function SetVehicleMudLevel(vehicle: number, mudLevel: number): void;
export declare function SetVehicleOnGroundProperly(vehicle: number, p1: number): boolean;
export declare function SetVehiclePetrolTankHealth(vehicle: number, health: number): void;
export declare function SetVehicleProvidesCover(vehicle: number, toggle: boolean): void;
export declare function SetVehicleShootAtTarget(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): void;
export declare function SetVehicleSnowLevel(vehicle: number, snowLevel: number): void;
export declare function SetVehicleSteerBias(vehicle: number, value: number): void;
export declare function SetVehicleStrong(vehicle: number, toggle: boolean): void;
export declare function SetVehicleTint(vehicle: number, tintId: number): void;
export declare function SetVehicleTyresCanBurst(vehicle: number, toggle: boolean): void;
export declare function SetVehicleUndriveable(vehicle: number, toggle: boolean): void;
export declare function SetVehicleWetLevel(vehicle: number, wetLevel: number): void;
export declare function SetVehicleWheelsCanBreak(vehicle: number, enabled: boolean): void;
export declare function SetVehicleWheelsCanBreakOffWhenBlowUp(vehicle: number, toggle: boolean): void;
export declare function SkipTimeInPlaybackRecordedVehicle(vehicle: number, time: number): void;
export declare function StartPlaybackRecordedVehicle(vehicle: number, recording: number, script: string, p3: boolean): void;
export declare function StartVehicleHorn(vehicle: number, duration: number, mode: string | number, forever: boolean): void;
export declare function StopPlaybackRecordedVehicle(vehicle: number): void;
export declare function TrackVehicleVisibility(vehicle: number): void;
// Hash functions
export declare function N_0x012701ed938b85de(p0: any, p1: any): void;
export declare function N_0x0355fe37240e2c77(p0: any, p1: any): void;
export declare function N_0x04f0579dbdd32f34(p0: any): void;
export declare function N_0x0516fae561276efc(p0: any): any;
export declare function N_0x065d03a9d6b2c6b5(p0: any, p1: any): void;
export declare function N_0x06a09a6e0c6d2a84(p0: any, p1: any): void;
export declare function N_0x0794199b25e499e1(p0: any, p1: any): void;
export declare function N_0x07e2e21e799080a0(p0: any, p1: any): void;
export declare function N_0x0893dafbfa67110e(vehicle: number, toggle: boolean): void;
export declare function N_0x09034479e6e3e269(p0: any, p1: any, p2: any): any;
export declare function N_0x09c970ae59abf6b2(vehicle: number, p1: boolean): void;
export declare function N_0x0ba4250d20007c2e(p0: any): any;
export declare function N_0x0cd7914d17a970ab(p0: any, p1: any): void;
export declare function N_0x0d5fdf0d36fa10cd(p0: any): void;
export declare function N_0x0e3bf7ed4169ec43(p0: any): any;
export declare function N_0x0e558d3a49d759d6(p0: any, p1: any): any;
export declare function N_0x0f7f603bde08c4d3(p0: any): void;
export declare function N_0x0fddee66e3465726(p0: any): any;
export declare function N_0x104d9a7b1c0d0783(p0: any, p1: any): void;
export declare function N_0x1098cda477890165(p0: any, p1: any): void;
export declare function N_0x1121b07088ed3013(p0: any): any;
export declare function N_0x1180a2974d251b7b(p0: any): any;
export declare function N_0x1240e8596a8308b9(p0: any, p1: any): void;
export declare function N_0x12f6c6ed3eff42de(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0x138398153824e332(): void;
export declare function N_0x13c190302369308b(p0: any): any;
export declare function N_0x13eb275bf81636d1(p0: any, p1: any): void;
export declare function N_0x14da8c4bc2ccd90a(p0: any): any;
export declare function N_0x15206e88ff7617df(p0: any, p1: any): void;
export declare function N_0x160c1b5ab48ab87c(p0: any, p1: any): void;
export declare function N_0x165be2001e5e4b75(p0: any): void;
export declare function N_0x16b86a49e072aa85(): void;
export declare function N_0x1716d787d9b94202(vehicle: number, p1: boolean): void;
export declare function N_0x172e9dd35858dcd7(p0: any): void;
export declare function N_0x18714953cced17d3(p0: any): any;
export declare function N_0x1a861f899ebbe17c(p0: any, p1: any): void;
export declare function N_0x1bfbafcc6760ff02(p0: any, p1: any): void;
export declare function N_0x1e8a921112891651(p0: any): [number, number, number];
export declare function N_0x1ef36558fbde2daa(vehicle: number): void;
export declare function N_0x201b8ed4ff7fe9f5(p0: any): void;
export declare function N_0x2045429505158d1a(p0: any): any;
export declare function N_0x2200ab13cbd10f4e(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): void;
export declare function N_0x226c6a4e3346d288(p0: any, p1: any): void;
export declare function N_0x23a3ab86e0807721(vehicle: number, toggle: boolean): void;
export declare function N_0x23f66c36f8e5eaab(p0: any, p1: any): void;
export declare function N_0x2701d01d5e18fc31(): boolean;
export declare function N_0x27e3f2b57209fa54(p0: any, p1: any): void;
export declare function N_0x288cbb414c3c2fbb(p0: any): any;
export declare function N_0x2a7413168f6cd5a8(): void;
export declare function N_0x2bb2b5bcf0df8008(p0: any, p1: any): void;
export declare function N_0x2c46d2a591d8c322(p0: any, p1: any, p2: any): any;
export declare function N_0x3053064f909b5f42(p0: any, p1: any): void;
export declare function N_0x30d86b2b7622d0eb(p0: any): any;
export declare function N_0x3137edc899e6dae4(p0: any, p1: any): void;
export declare function N_0x316cdb5b6e8f4110(p0: any, p1: any, p2: any): any;
export declare function N_0x31f343383f19c987(p0: any, p1: any, p2: any): void;
export declare function N_0x331cbd247fc5daa8(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
export declare function N_0x33992a808df1c1ba(vehicle: number, p1: boolean): void;
export declare function N_0x34bcf6209b9668a7(p0: any, p1: any): void;
export declare function N_0x35d302397e524939(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): [number, number, number];
export declare function N_0x35dc1877312fba0f(p0: any): void;
export declare function N_0x3660bcab3a6bb734(p0: any): void;
export declare function N_0x37d238be69f7378a(p0: any): any;
export declare function N_0x38e7dd70a242d5cb(p0: any, p1: any): void;
export declare function N_0x3abfa128f5bf5a70(p0: any, p1: any, p2: any): void;
export declare function N_0x3c9628a811cbd724(p0: any): any;
export declare function N_0x3d86997a86feef0d(p0: any, p1: any): void;
export declare function N_0x404527bc03da0e6c(p0: any): any;
export declare function N_0x41365db586cd9e8e(p0: any, p1: any): void;
export declare function N_0x41503629d1139abc(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function N_0x41cda90ee3450921(p0: any): void;
export declare function N_0x41f0b254ddf71473(p0: any): void;
export declare function N_0x42404d57d621601a(p0: any): any;
export declare function N_0x424ffcb9f0d2d4b5(p0: any, p1: any): void;
export declare function N_0x427c919e9809e370(p0: any, p1: any): void;
export declare function N_0x4402960666000e62(p0: any, p1: any): any;
export declare function N_0x45853f4e17d847d5(p0: any): any;
export declare function N_0x485b05ef05b9aee9(p0: any, p1: any): void;
export declare function N_0x4c05b42a8d937796(): void;
export declare function N_0x4c60c333f9cca2b6(p0: any, p1: any): void;
export declare function N_0x5136b284b67b35c7(p0: any): any;
export declare function N_0x51c7694e140fae43(p0: any): any;
export declare function N_0x54cbdd6e1b4cb4df(p0: any): void;
export declare function N_0x5aadc7bbbb1bceeb(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function N_0x5b1a26bb18e7d451(p0: any): any;
export declare function N_0x6090a031c69f384e(p0: any, p1: any): void;
export declare function N_0x60b7d1dcc312697d(p0: any): any;
export declare function N_0x615b3b8e73634509(p0: any, p1: any): void;
export declare function N_0x63509ddf102e08e8(p0: any, p1: any): void;
export declare function N_0x635423d55ca84fc8(p0: any): any;
export declare function N_0x6355602c02edc6df(p0: any, p1: any): void;
export declare function N_0x63dc1f22c903b709(vehicle: number, p1: boolean): void;
export declare function N_0x6703872ec09bc158(p0: any, p1: any): void;
export declare function N_0x671a07c9a1cd50a5(p0: any): any;
export declare function N_0x67995318f5faa496(p0: any): any;
export declare function N_0x6835afea10e186f4(p0: any, p1: any): void;
export declare function N_0x68830738a6bfb370(p0: any, p1: any): void;
export declare function N_0x697df68f3a761a50(p0: any): void;
export declare function N_0x6b34be961f639e21(p0: any, p1: any): void;
export declare function N_0x6b53f4b811e583d2(p0: any, p1: any): void;
export declare function N_0x6c87f49bfa181db5(p0: any, p1: any, p2: any): any;
export declare function N_0x6de072ac8a95ffc1(p0: any, p1: any): void;
export declare function N_0x6e585a616abb8401(p0: any): any;
export declare function N_0x6ea1273d525427f4(p0: any, p1: any, p2: any): void;
export declare function N_0x6fd7bdf10304363a(p0: any, p1: any): void;
export declare function N_0x703d4fb366da4452(p0: any, p1: any): void;
export declare function N_0x718eb706b6e998a0(p0: any): void;
export declare function N_0x73118a3ee9c9b6db(p0: any, p1: any, p2: any): void;
export declare function N_0x7408b5c66ba31adb(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any, p7: any, p8: any, p9: any, p10: any): void;
export declare function N_0x750d42c013f64ae7(p0: any, p1: any): void;
export declare function N_0x7549b9e841940695(vehicle: number, p1: boolean): void;
export declare function N_0x75b49acd73617437(vehicle: number, p1: boolean): void;
export declare function N_0x762fdc4c19e5a981(p0: any, p1: any): void;
export declare function N_0x7840576c50a13dba(p0: any, p1: any): void;
export declare function N_0x785639d89f8451ab(p0: any, p1: any): [number, number, number];
export declare function N_0x787e43477746876f(p0: any): void;
export declare function N_0x7be0746539def0c8(p0: any, p1: any): any;
export declare function N_0x7c06330bfdda182e(p0: any): void;
export declare function N_0x7c9e45a4ced2e8da(p0: any, p1: any): void;
export declare function N_0x7f8e2b131e1dca6c(p0: any, p1: boolean): void;
export declare function N_0x80ddccb2f4a3eb57(ped: number, vehicle: number, p2: boolean, p3: boolean, p4: boolean): boolean;
export declare function N_0x8379e05871ad24e0(): void;
export declare function N_0x850ce59dec2028f3(p0: any, p1: any): void;
export declare function N_0x85d39f5e3b6d7eb0(p0: any, p1: any, p2: any): any;
export declare function N_0x865fec2fa899f29c(p0: any): any;
export declare function N_0x86afc343cf7f0b34(p0: any, p1: any, p2: any, p3: any, p4: any): any;
export declare function N_0x86fa6d8b48667d75(p0: any): any;
export declare function N_0x87344305778e5415(p0: any, p1: any): void;
export declare function N_0x873aaf600cc36dac(p0: any): void;
export declare function N_0x877ea24eb1614495(p0: any, p1: any, p2: any): any;
export declare function N_0x87b974e54c71ba7b(p0: any, p1: any): void;
export declare function N_0x8878ff3eee2868a9(p0: any, p1: any): void;
export declare function N_0x8c6d9a399126c194(p0: any, p1: any): void;
export declare function N_0x8d3230a0ed7de39f(vehicle: number, p1: boolean): void;
export declare function N_0x8decd262602548b9(p0: any, p1: any): void;
export declare function N_0x8df5f6a19f99f0d5(p0: any, p1: any): any;
export declare function N_0x8e5da070bad3279e(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0x8f75941c86eebfca(vehicle: number, p1: boolean): void;
export declare function N_0x9868c0d0134855f7(p0: any): void;
export declare function N_0x98a7598c579ee871(p0: any, p1: any, p2: any): void;
export declare function N_0x9cc94a948eaf5372(p0: any, p1: any): any;
export declare function N_0x9d12796ef4bf9ea9(p0: any): void;
export declare function N_0x9e8711c81aa17876(p0: any, p1: any): void;
export declare function N_0xa13028e22564a1bd(p0: any, p1: any): void;
export declare function N_0xa230a5dde12ed374(p0: any): void;
export declare function N_0xa72b1bf3857b94d7(p0: any, p1: any): void;
export declare function N_0xa7966807953a18ee(p0: any, p1: any): void;
export declare function N_0xa9e185d498b9ac67(p0: any, p1: any): any;
export declare function N_0xae7e66a61e7c17a5(p0: any, p1: any): void;
export declare function N_0xaf787e081ac4a8ee(p0: any): any;
export declare function N_0xb36d3ec70963be60(p0: any, p1: any): any;
export declare function N_0xb4241ad8f5aee9ed(p0: any): any;
export declare function N_0xb42c87521d1bdd2f(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0xb961dd799a837bd7(): void;
export declare function N_0xb9d5bdda88e1bb66(p0: any): any;
export declare function N_0xba958f68031ddbfc(p0: any, p1: any): [number, number, number];
export declare function N_0xbd3c4a2ed509205e(p0: any): any;
export declare function N_0xc1842f40fd501da2(p0: any, p1: boolean): void;
export declare function N_0xc29996a337bdd099(p0: any): any;
export declare function N_0xc2e62678d602853c(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): void;
export declare function N_0xc325a6baa62cf8a2(p0: any, p1: any): void;
export declare function N_0xc351394b932a6a50(p0: any): void;
export declare function N_0xc372b6a88f6e4ad8(p0: any, p1: any, p2: any): void;
export declare function N_0xc399cc89fba05da0(p0: any, p1: any): void;
export declare function N_0xc4a2c11fc0d41916(p0: any, p1: any): void;
export declare function N_0xc6d7ddc843176701(p0: any): any;
export declare function N_0xc84e138448507567(vehicle: number, p1: boolean): void;
export declare function N_0xc9ea26893c9e4024(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function N_0xcacab2b123bbdbd6(p0: any, p1: any, p2: any): any;
export declare function N_0xcaff2c9747103c02(p0: any, p1: any, p2: any): any;
export declare function N_0xcb2ca620c48bc875(p0: any, p1: any): any;
export declare function N_0xcbc7b6f9a56b79f6(p0: any, p1: any): void;
export declare function N_0xcbf88256e44d5d39(p0: any, p1: any): void;
export declare function N_0xce1531927ad6c9f8(p0: any, p1: any): void;
export declare function N_0xceb1f1eed484a5b4(p0: any, p1: any): void;
export declare function N_0xcec4ca2cab8fa98c(vehicle: number, p1: boolean): void;
export declare function N_0xcf342503ca4c8df1(p0: any, p1: any): void;
export declare function N_0xcf9da72002fc16bf(p0: any, p1: any, p2: any): void;
export declare function N_0xcfe122ec635cc2b2(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0xd0116df21e6c7b36(p0: any, p1: any): any;
export declare function N_0xd0aabe5b9f8fa589(p0: any, p1: any): void;
export declare function N_0xd0ba1853d76683c8(p0: any, p1: any, p2: any, p3: any, p4: any): void;
export declare function N_0xd1df5e54f4acbe1a(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any, p6: any): any;
export declare function N_0xd1efa8d68bf5d63d(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0xd21a3d421e7f09f7(p0: any, p1: any): void;
export declare function N_0xd4907ef4334c7602(p0: any, p1: any): void;
export declare function N_0xd798df5db67b1659(p0: any): any;
export declare function N_0xd826690b5cf3beff(p0: any, p1: any): void;
export declare function N_0xd9bf3ed8efb67ea3(p0: any, p1: any, p2: any, p3: any, p4: any): any;
export declare function N_0xdc0556d0f484ecaa(p0: any): void;
export declare function N_0xdc69f6913cca0b99(p0: any, p1: any): void;
export declare function N_0xdd100ce1ebbf37e3(p0: any, p1: any): void;
export declare function N_0xde8c5b9f65017fa1(p0: any): any;
export declare function N_0xe12f5ed49f44d40d(p0: any): void;
export declare function N_0xe1a83d4a3b5d7938(p0: any): any;
export declare function N_0xe1c0f8781bf130c2(p0: any, p1: any): any;
export declare function N_0xe682002db1f30669(p0: any): void;
export declare function N_0xe6bd7dd3fd474415(p0: any, p1: any): void;
export declare function N_0xe6c5e2125eb210c1(p0: any, p1: any, p2: any): void;
export declare function N_0xe777ddf3e78397e8(p0: any): any;
export declare function N_0xe78993ff9022c064(p0: any): void;
export declare function N_0xe887bd31d97793f6(p0: any): any;
export declare function N_0xef28a614b4b264b8(p0: any, p1: any): void;
export declare function N_0xf05dfaf1adfef2cd(p0: any, p1: any, p2: any, p3: any, p4: any, p5: any): any;
export declare function N_0xf489f94bfee12bb0(p0: any, p1: any): void;
export declare function N_0xf57db8e83dcd8349(p0: any): any;
export declare function N_0xf5ea41c1408695fb(p0: any, p1: any, p2: any, p3: any): any;
export declare function N_0xf5ffb08976911b50(p0: any, p1: any, p2: any, p3: any): void;
export declare function N_0xf6e3d38869d0f7ad(p0: any): void;
export declare function N_0xf8f7da13cfbd4532(p0: any, p1: any): void;
export declare function N_0xfc4f15a7dddc47b1(p0: any, p1: any): void;
export declare function N_0xff2b1f59fb892f14(p0: any): void;
export declare function N_0xfffe15b433300b8c(p0: any, p1: any, p2: any): void;
